// The rules a write-up names, and where to read them.
//
// D&D's rules text is not ours to reproduce, and nothing here reproduces any:
// this is a list of NAMES and the address of a page somebody else wrote. That
// is also why it is a link rather than a tooltip — the useful thing a reader
// wants mid-recap is the actual rule, and the only honest way to give them that
// is to send them to it.
//
// TWO EDITIONS, and they are genuinely different lists. 2024 dropped spells the
// 2014 books had and added others, so every entry carries which wikis have it
// and a campaign only links what its own edition can answer. A link to a page
// that 404s is worse than no link, and this is the only way to be sure.
//
// GENERATED, from each wiki's own spell index. 570-odd names and slugs typed by
// hand would be 570 chances to misspell one; taken from the index, a slug is
// right by construction. Regenerate rather than edit — see the note in
// test/rules.test.js about what to re-check if the shape of those pages moves.
//
// WHAT IS NOT HERE, and why. Conditions, monsters, skills and classes are the
// terms a session recap says most, and NEITHER wiki has a page for any of them:
// /conditions, /grappled, /monster:goblin, /class:wizard and every variation
// tried are all 404 on both. Checked 2026-09-04, not assumed. So this links
// spells, which both wikis do publish per-page, and nothing else.

// name, slug, and which wikis have it: 1 = 2014, 2 = 2024, 3 = both.
//
// Seventeen spells appear twice, under one name and two slugs, and that is not
// a duplicate: the two wikis slugify an apostrophe differently — dnd5e writes
// bigbys-hand where dnd2024 writes bigby-s-hand — so each edition needs its own
// row to have an address that resolves. rulesFor() still answers one entry per
// name per edition, which is all the reader ever sees.
const SPELLS = [
  ['Absorb Elements', 'absorb-elements', 1],
  ['Acid Splash', 'acid-splash', 3],
  ['Aganazzar\'s Scorcher', 'aganazzars-scorcher', 1],
  ['Air Bubble', 'air-bubble', 1],
  ['Alter Self', 'alter-self', 3],
  ['Alustriel\'s Mooncloak', 'alustriel-s-mooncloak', 2],
  ['Animal Friendship', 'animal-friendship', 3],
  ['Animal Messenger', 'animal-messenger', 3],
  ['Animal Shapes', 'animal-shapes', 3],
  ['Animate Dead', 'animate-dead', 3],
  ['Animate Objects', 'animate-objects', 3],
  ['Antilife Shell', 'antilife-shell', 3],
  ['Antimagic Field', 'antimagic-field', 3],
  ['Arcane Eye', 'arcane-eye', 3],
  ['Arcane Gate', 'arcane-gate', 3],
  ['Arcane Lock', 'arcane-lock', 3],
  ['Arcane Vigor', 'arcane-vigor', 2],
  ['Armor of Agathys', 'armor-of-agathys', 3],
  ['Arms of Hadar', 'arms-of-hadar', 3],
  ['Ashardalon\'s Stride', 'ashardalons-stride', 1],
  ['Astral Flood', 'astral-flood', 2],
  ['Astral Projection', 'astral-projection', 3],
  ['Aura of Evasion', 'aura-of-evasion', 2],
  ['Aura of Life', 'aura-of-life', 3],
  ['Aura of Purity', 'aura-of-purity', 3],
  ['Aura of Vitality', 'aura-of-vitality', 3],
  ['Banishing Smite', 'banishing-smite', 3],
  ['Barkskin', 'barkskin', 3],
  ['Battle Familiar', 'battle-familiar', 2],
  ['Beacon of Hope', 'beacon-of-hope', 3],
  ['Beast Bond', 'beast-bond', 1],
  ['Beast Sense', 'beast-sense', 3],
  ['Befuddlement', 'befuddlement', 2],
  ['Bestow Curse', 'bestow-curse', 3],
  ['Bigby\'s Hand', 'bigbys-hand', 1],
  ['Bigby\'s Hand', 'bigby-s-hand', 2],
  ['Blade Barrier', 'blade-barrier', 3],
  ['Blade of Disaster', 'blade-of-disaster', 3],
  ['Blade Ward', 'blade-ward', 3],
  ['Blinding Smite', 'blinding-smite', 3],
  ['Bones of the Earth', 'bones-of-the-earth', 1],
  ['Booming Blade', 'booming-blade', 1],
  ['Borrowed Knowledge', 'borrowed-knowledge', 1],
  ['Branding Smite', 'branding-smite', 1],
  ['Burning Hands', 'burning-hands', 3],
  ['Buzzing Bee', 'buzzing-bee', 2],
  ['Cacophonic Shield', 'cacophonic-shield', 2],
  ['Call Lightning', 'call-lightning', 3],
  ['Calm Emotions', 'calm-emotions', 3],
  ['Cause Fear', 'cause-fear', 1],
  ['Chain Lightning', 'chain-lightning', 3],
  ['Chaos Bolt', 'chaos-bolt', 1],
  ['Charm Monster', 'charm-monster', 3],
  ['Charm Person', 'charm-person', 3],
  ['Chill Touch', 'chill-touch', 3],
  ['Chromatic Orb', 'chromatic-orb', 3],
  ['Circle of Death', 'circle-of-death', 3],
  ['Circle of Power', 'circle-of-power', 3],
  ['Cloud of Daggers', 'cloud-of-daggers', 3],
  ['Cloudkill', 'cloudkill', 3],
  ['Color Spray', 'color-spray', 3],
  ['Commune with Nature', 'commune-with-nature', 3],
  ['Compelled Duel', 'compelled-duel', 3],
  ['Comprehend Languages', 'comprehend-languages', 3],
  ['Cone of Cold', 'cone-of-cold', 3],
  ['Conjure Animals', 'conjure-animals', 3],
  ['Conjure Barrage', 'conjure-barrage', 3],
  ['Conjure Celestial', 'conjure-celestial', 3],
  ['Conjure Constructs', 'conjure-constructs', 2],
  ['Conjure Elemental', 'conjure-elemental', 3],
  ['Conjure Fey', 'conjure-fey', 3],
  ['Conjure Minor Elementals', 'conjure-minor-elementals', 3],
  ['Conjure Tools', 'conjure-tools', 2],
  ['Conjure Volley', 'conjure-volley', 3],
  ['Conjure Woodland Beings', 'conjure-woodland-beings', 3],
  ['Contact Other Plane', 'contact-other-plane', 3],
  ['Continual Flame', 'continual-flame', 3],
  ['Control Flames', 'control-flames', 1],
  ['Control Water', 'control-water', 3],
  ['Control Weather', 'control-weather', 3],
  ['Control Winds', 'control-winds', 1],
  ['Cordon of Arrows', 'cordon-of-arrows', 3],
  ['Counterspell', 'counterspell', 3],
  ['Create Bonfire', 'create-bonfire', 1],
  ['Create Food and Water', 'create-food-and-water', 3],
  ['Create Homunculus', 'create-homunculus', 1],
  ['Create Magen', 'create-magen', 1],
  ['Create or Destroy Water', 'create-or-destroy-water', 3],
  ['Create Spelljamming Helm', 'create-spelljamming-helm', 1],
  ['Create Undead', 'create-undead', 3],
  ['Crown of Madness', 'crown-of-madness', 3],
  ['Crown of Stars', 'crown-of-stars', 1],
  ['Crusader\'s Mantle', 'crusaders-mantle', 1],
  ['Crusader\'s Mantle', 'crusader-s-mantle', 2],
  ['Cure Wounds', 'cure-wounds', 3],
  ['Dancing Lights', 'dancing-lights', 3],
  ['Danse Macabre', 'danse-macabre', 1],
  ['Dark Star', 'dark-star', 1],
  ['Darkvision', 'darkvision', 3],
  ['Death Armor', 'death-armor', 2],
  ['Death Ward', 'death-ward', 3],
  ['Delayed Blast Fireball', 'delayed-blast-fireball', 3],
  ['Demiplane', 'demiplane', 3],
  ['Deryan\'s Helpful Homunculi', 'deryan-s-helpful-homunculi', 2],
  ['Destructive Wave', 'destructive-wave', 3],
  ['Detect Evil and Good', 'detect-evil-and-good', 3],
  ['Detect Magic', 'detect-magic', 3],
  ['Detect Poison and Disease', 'detect-poison-and-disease', 3],
  ['Detect Thoughts', 'detect-thoughts', 3],
  ['Dimension Door', 'dimension-door', 3],
  ['Disguise Self', 'disguise-self', 3],
  ['Dispel Evil and Good', 'dispel-evil-and-good', 3],
  ['Dispel Magic', 'dispel-magic', 3],
  ['Disruptive Tune', 'disruptive-tune', 2],
  ['Dissonant Whispers', 'dissonant-whispers', 3],
  ['Distort Value', 'distort-value', 1],
  ['Distorted Distance', 'distorted-distance', 2],
  ['Divine Favor', 'divine-favor', 3],
  ['Divine Smite', 'divine-smite', 2],
  ['Divine Word', 'divine-word', 3],
  ['Dominate Beast', 'dominate-beast', 3],
  ['Dominate Monster', 'dominate-monster', 3],
  ['Dominate Person', 'dominate-person', 3],
  ['Doomtide', 'doomtide', 2],
  ['Draconic Transformation', 'draconic-transformation', 1],
  ['Dragon\'s Breath', 'dragons-breath', 1],
  ['Dragon\'s Breath', 'dragon-s-breath', 2],
  ['Drawmij\'s Instant Summons', 'drawmijs-instant-summons', 1],
  ['Drawmij\'s Instant Summons', 'drawmij-s-instant-summons', 2],
  ['Dream of the Blue Veil', 'dream-of-the-blue-veil', 1],
  ['Druid Grove', 'druid-grove', 1],
  ['Druidcraft', 'druidcraft', 3],
  ['Dueling Ground', 'dueling-ground', 2],
  ['Dust Devil', 'dust-devil', 1],
  ['Earth Tremor', 'earth-tremor', 1],
  ['Earthbind', 'earthbind', 1],
  ['Eldritch Blast', 'eldritch-blast', 3],
  ['Elemental Bane', 'elemental-bane', 1],
  ['Elemental Weapon', 'elemental-weapon', 3],
  ['Elementalism', 'elementalism', 2],
  ['Elminster\'s Effulgent Spheres', 'elminster-s-effulgent-spheres', 2],
  ['Elminster\'s Elusion', 'elminster-s-elusion', 2],
  ['Encode Thoughts', 'encode-thoughts', 1],
  ['Enemies Abound', 'enemies-abound', 1],
  ['Enervation', 'enervation', 3],
  ['Enhance Ability', 'enhance-ability', 3],
  ['Ensnaring Strike', 'ensnaring-strike', 3],
  ['Entrancing Mirrors', 'entrancing-mirrors', 2],
  ['Erupting Earth', 'erupting-earth', 1],
  ['Etherealness', 'etherealness', 3],
  ['Evard\'s Black Tentacles', 'evards-black-tentacles', 1],
  ['Evard\'s Black Tentacles', 'evard-s-black-tentacles', 2],
  ['Expeditious Retreat', 'expeditious-retreat', 3],
  ['Eyebite', 'eyebite', 3],
  ['Faerie Fire', 'faerie-fire', 3],
  ['False Life', 'false-life', 3],
  ['Far Step', 'far-step', 1],
  ['Fast Friends', 'fast-friends', 1],
  ['Feather Fall', 'feather-fall', 3],
  ['Feeblemind', 'feeblemind', 1],
  ['Feign Death', 'feign-death', 3],
  ['Feign Interest', 'feign-interest', 2],
  ['Festering Blast', 'festering-blast', 2],
  ['Find Familiar', 'find-familiar', 3],
  ['Find Greater Steed', 'find-greater-steed', 1],
  ['Find Steed', 'find-steed', 3],
  ['Find the Path', 'find-the-path', 3],
  ['Find Traps', 'find-traps', 3],
  ['Finger of Death', 'finger-of-death', 3],
  ['Fire Bolt', 'fire-bolt', 3],
  ['Fire Shield', 'fire-shield', 3],
  ['Fire Storm', 'fire-storm', 3],
  ['Fireball', 'fireball', 3],
  ['Fizban\'s Platinum Shield', 'fizbans-platinum-shield', 1],
  ['Flame Arrows', 'flame-arrows', 1],
  ['Flame Blade', 'flame-blade', 3],
  ['Flame Strike', 'flame-strike', 3],
  ['Flaming Sphere', 'flaming-sphere', 3],
  ['Flesh to Stone', 'flesh-to-stone', 3],
  ['Flock of Familiars', 'flock-of-familiars', 1],
  ['Fog Cloud', 'fog-cloud', 3],
  ['Forbiddance', 'forbiddance', 3],
  ['Forcecage', 'forcecage', 3],
  ['Fortune\'s Favor', 'fortunes-favor', 1],
  ['Fount of Moonlight', 'fount-of-moonlight', 2],
  ['Fractured Awareness', 'fractured-awareness', 2],
  ['Freedom of Movement', 'freedom-of-movement', 3],
  ['Frost Fingers', 'frost-fingers', 1],
  ['Frostbite', 'frostbite', 1],
  ['Galder\'s Speedy Courier', 'galders-speedy-courier', 1],
  ['Galder\'s Tower', 'galders-tower', 1],
  ['Gaseous Form', 'gaseous-form', 3],
  ['Gate Seal', 'gate-seal', 1],
  ['Gentle Repose', 'gentle-repose', 3],
  ['Giant Insect', 'giant-insect', 3],
  ['Gift of Alacrity', 'gift-of-alacrity', 1],
  ['Gift of Gab', 'gift-of-gab', 1],
  ['Glibness', 'glibness', 3],
  ['Globe of Invulnerability', 'globe-of-invulnerability', 3],
  ['Glyph of Warding', 'glyph-of-warding', 3],
  ['Goodberry', 'goodberry', 3],
  ['Grasping Vine', 'grasping-vine', 3],
  ['Grave Ground', 'grave-ground', 2],
  ['Gravity Fissure', 'gravity-fissure', 1],
  ['Gravity Sinkhole', 'gravity-sinkhole', 1],
  ['Greater Invisibility', 'greater-invisibility', 3],
  ['Greater Restoration', 'greater-restoration', 3],
  ['Guardian of Faith', 'guardian-of-faith', 3],
  ['Guardian of Nature', 'guardian-of-nature', 1],
  ['Guards and Wards', 'guards-and-wards', 3],
  ['Guiding Bolt', 'guiding-bolt', 3],
  ['Gust of Wind', 'gust-of-wind', 3],
  ['Hail of Thorns', 'hail-of-thorns', 3],
  ['Hallucinatory Terrain', 'hallucinatory-terrain', 3],
  ['Healing Spirit', 'healing-spirit', 1],
  ['Healing Word', 'healing-word', 3],
  ['Heat Metal', 'heat-metal', 3],
  ['Hellish Rebuke', 'hellish-rebuke', 3],
  ['Heroes\' Feast', 'heroes-feast', 3],
  ['Hold Monster', 'hold-monster', 3],
  ['Hold Person', 'hold-person', 3],
  ['Holy Aura', 'holy-aura', 3],
  ['Holy Star of Mystra', 'holy-star-of-mystra', 2],
  ['Holy Weapon', 'holy-weapon', 1],
  ['Homunculus Servant', 'homunculus-servant', 2],
  ['Hunger Of Hadar', 'hunger-of-hadar', 3],
  ['Hunter\'s Mark', 'hunters-mark', 1],
  ['Hunter\'s Mark', 'hunter-s-mark', 2],
  ['Hypnotic Pattern', 'hypnotic-pattern', 3],
  ['Ice Knife', 'ice-knife', 3],
  ['Ice Storm', 'ice-storm', 3],
  ['Illusory Dragon', 'illusory-dragon', 3],
  ['Illusory Script', 'illusory-script', 3],
  ['Immolation', 'immolation', 1],
  ['Immovable Object', 'immovable-object', 1],
  ['Incendiary Cloud', 'incendiary-cloud', 3],
  ['Incite Greed', 'incite-greed', 1],
  ['Infernal Calling', 'infernal-calling', 1],
  ['Inflict Doubt', 'inflict-doubt', 2],
  ['Inflict Wounds', 'inflict-wounds', 3],
  ['Insect Plague', 'insect-plague', 3],
  ['Insidious Rhythm', 'insidious-rhythm', 2],
  ['Intellect Fortress', 'intellect-fortress', 1],
  ['Investiture of Flame', 'investiture-of-flame', 1],
  ['Investiture of Ice', 'investiture-of-ice', 1],
  ['Investiture of Stone', 'investiture-of-stone', 1],
  ['Investiture of Wind', 'investiture-of-wind', 1],
  ['Iron Body', 'iron-body', 2],
  ['Jallarzi\'s Storm of Radiance', 'jallarzi-s-storm-of-radiance', 2],
  ['Jim\'s Glowing Coin', 'jims-glowing-coin', 1],
  ['Jim\'s Magic Missile', 'jims-magic-missile', 1],
  ['Kinetic Jaunt', 'kinetic-jaunt', 1],
  ['Laeral\'s Silver Lance', 'laeral-s-silver-lance', 2],
  ['Legend Lore', 'legend-lore', 3],
  ['Leomund\'s Lamentable Belaborment', 'leomund-s-lamentable-belaborment', 2],
  ['Leomund\'s Secret Chest', 'leomunds-secret-chest', 3],
  ['Leomund\'s Tiny Hut', 'leomunds-tiny-hut', 1],
  ['Leomund\'s Tiny Hut', 'leomund-s-tiny-hut', 2],
  ['Lesser Restoration', 'lesser-restoration', 3],
  ['Life Transference', 'life-transference', 1],
  ['Lightning Arrow', 'lightning-arrow', 3],
  ['Lightning Bolt', 'lightning-bolt', 3],
  ['Lightning Lure', 'lightning-lure', 1],
  ['Lightning Ring', 'lightning-ring', 2],
  ['Locate Animals or Plants', 'locate-animals-or-plants', 3],
  ['Locate Creature', 'locate-creature', 3],
  ['Locate Object', 'locate-object', 3],
  ['Longstrider', 'longstrider', 3],
  ['Maddening Darkness', 'maddening-darkness', 1],
  ['Mage Armor', 'mage-armor', 3],
  ['Mage Hand', 'mage-hand', 3],
  ['Magic Circle', 'magic-circle', 3],
  ['Magic Jar', 'magic-jar', 3],
  ['Magic Missile', 'magic-missile', 3],
  ['Magic Mouth', 'magic-mouth', 3],
  ['Magic Stone', 'magic-stone', 1],
  ['Magic Weapon', 'magic-weapon', 3],
  ['Magnify Gravity', 'magnify-gravity', 1],
  ['Major Image', 'major-image', 3],
  ['Mass Cure Wounds', 'mass-cure-wounds', 3],
  ['Mass Heal', 'mass-heal', 3],
  ['Mass Healing Word', 'mass-healing-word', 3],
  ['Mass Polymorph', 'mass-polymorph', 1],
  ['Mass Suggestion', 'mass-suggestion', 3],
  ['Maximillian\'s Earthen Grasp', 'maximillians-earthen-grasp', 1],
  ['Meld into Stone', 'meld-into-stone', 3],
  ['Melf\'s Acid Arrow', 'melfs-acid-arrow', 3],
  ['Melf\'s Minute Meteors', 'melfs-minute-meteors', 1],
  ['Mental Prison', 'mental-prison', 1],
  ['Meteor Swarm', 'meteor-swarm', 3],
  ['Mighty Fortress', 'mighty-fortress', 1],
  ['Mind Blank', 'mind-blank', 3],
  ['Mind Sliver', 'mind-sliver', 3],
  ['Mind Spike', 'mind-spike', 3],
  ['Minor Illusion', 'minor-illusion', 3],
  ['Mirage Arcane', 'mirage-arcane', 3],
  ['Mirror Image', 'mirror-image', 3],
  ['Misty Step', 'misty-step', 3],
  ['Modify Memory', 'modify-memory', 3],
  ['Mold Earth', 'mold-earth', 1],
  ['Moment of Prescience', 'moment-of-prescience', 2],
  ['Moonbeam', 'moonbeam', 3],
  ['Mordenkainen\'s Faithful Hound', 'mordenkainens-faithful-hound', 1],
  ['Mordenkainen\'s Faithful Hound', 'mordenkainen-s-faithful-hound', 2],
  ['Mordenkainen\'s Lucubration', 'mordenkainen-s-lucubration', 2],
  ['Mordenkainen\'s Magnificent Mansion', 'mordenkainens-magnificent-mansion', 1],
  ['Mordenkainen\'s Magnificent Mansion', 'mordenkainen-s-magnificent-mansion', 2],
  ['Mordenkainen\'s Private Sanctum', 'mordenkainens-private-sanctum', 1],
  ['Mordenkainen\'s Private Sanctum', 'mordenkainen-s-private-sanctum', 2],
  ['Mordenkainen\'s Sword', 'mordenkainens-sword', 1],
  ['Mordenkainen\'s Sword', 'mordenkainen-s-sword', 2],
  ['Motivational Speech', 'motivational-speech', 1],
  ['Move Earth', 'move-earth', 3],
  ['Nathair\'s Mischief', 'nathairs-mischief', 1],
  ['Negative Energy Flood', 'negative-energy-flood', 3],
  ['Nondetection', 'nondetection', 3],
  ['Nystul\'s Magic Aura', 'nystuls-magic-aura', 1],
  ['Nystul\'s Magic Aura', 'nystul-s-magic-aura', 2],
  ['Otiluke\'s Freezing Sphere', 'otilukes-freezing-sphere', 1],
  ['Otiluke\'s Freezing Sphere', 'otiluke-s-freezing-sphere', 2],
  ['Otiluke\'s Resilient Sphere', 'otilukes-resilient-sphere', 3],
  ['Otto\'s Irresistible Dance', 'ottos-irresistible-dance', 1],
  ['Otto\'s Irresistible Dance', 'otto-s-irresistible-dance', 2],
  ['Pass Without Trace', 'pass-without-trace', 3],
  ['Phantasmal Force', 'phantasmal-force', 3],
  ['Phantasmal Killer', 'phantasmal-killer', 3],
  ['Phantom Steed', 'phantom-steed', 3],
  ['Pinky Swear', 'pinky-swear', 2],
  ['Planar Ally', 'planar-ally', 3],
  ['Planar Binding', 'planar-binding', 3],
  ['Plane Shift', 'plane-shift', 3],
  ['Plant Growth', 'plant-growth', 3],
  ['Poison Spray', 'poison-spray', 3],
  ['Power Word Fortify', 'power-word-fortify', 2],
  ['Prayer of Healing', 'prayer-of-healing', 3],
  ['Prestidigitation', 'prestidigitation', 3],
  ['Primal Savagery', 'primal-savagery', 1],
  ['Primordial Ward', 'primordial-ward', 1],
  ['Prismatic Spray', 'prismatic-spray', 3],
  ['Prismatic Wall', 'prismatic-wall', 3],
  ['Produce Flame', 'produce-flame', 3],
  ['Programmed Illusion', 'programmed-illusion', 3],
  ['Project Image', 'project-image', 3],
  ['Protection from Energy', 'protection-from-energy', 3],
  ['Protection from Evil and Good', 'protection-from-evil-and-good', 3],
  ['Protection from Poison', 'protection-from-poison', 3],
  ['Psychic Scream', 'psychic-scream', 1],
  ['Pulse Wave', 'pulse-wave', 1],
  ['Purify Food and Drink', 'purify-food-and-drink', 3],
  ['Pyrotechnics', 'pyrotechnics', 1],
  ['Quick Clothier', 'quick-clothier', 2],
  ['Raise Dead', 'raise-dead', 3],
  ['Rary\'s Telepathic Bond', 'rarys-telepathic-bond', 1],
  ['Rary\'s Telepathic Bond', 'rary-s-telepathic-bond', 2],
  ['Raulothim\'s Psychic Lance', 'raulothims-psychic-lance', 1],
  ['Ravenous Void', 'ravenous-void', 1],
  ['Ray of Enfeeblement', 'ray-of-enfeeblement', 3],
  ['Ray of Frost', 'ray-of-frost', 3],
  ['Ray of Sickness', 'ray-of-sickness', 3],
  ['Reality Break', 'reality-break', 1],
  ['Remove Curse', 'remove-curse', 3],
  ['Reverse Gravity', 'reverse-gravity', 3],
  ['Reweave Fate', 'reweave-fate', 2],
  ['Rime\'s Binding Ice', 'rimes-binding-ice', 1],
  ['Rope Trick', 'rope-trick', 3],
  ['Sacred Flame', 'sacred-flame', 3],
  ['Sapping Sting', 'sapping-sting', 1],
  ['Scorching Ray', 'scorching-ray', 3],
  ['Searing Orb', 'searing-orb', 2],
  ['Searing Smite', 'searing-smite', 3],
  ['See Invisibility', 'see-invisibility', 3],
  ['Shadow Blade', 'shadow-blade', 1],
  ['Shadow Of Moil', 'shadow-of-moil', 1],
  ['Shape Water', 'shape-water', 1],
  ['Shapechange', 'shapechange', 3],
  ['Shield of Faith', 'shield-of-faith', 3],
  ['Shillelagh', 'shillelagh', 3],
  ['Shining Smite', 'shining-smite', 2],
  ['Shocking Grasp', 'shocking-grasp', 3],
  ['Sickening Radiance', 'sickening-radiance', 1],
  ['Silent Image', 'silent-image', 3],
  ['Silvery Barbs', 'silvery-barbs', 1],
  ['Simbul\'s Synostodweomer', 'simbul-s-synostodweomer', 2],
  ['Simulacrum', 'simulacrum', 3],
  ['Skill Empowerment', 'skill-empowerment', 1],
  ['Skywrite', 'skywrite', 1],
  ['Sleet Storm', 'sleet-storm', 3],
  ['Snilloc\'s Snowball Swarm', 'snillocs-snowball-swarm', 1],
  ['Songal\'s Elemental Suffusion', 'songal-s-elemental-suffusion', 2],
  ['Sorcerous Burst', 'sorcerous-burst', 2],
  ['Soul Cage', 'soul-cage', 1],
  ['Spare the Dying', 'spare-the-dying', 3],
  ['Speak with Animals', 'speak-with-animals', 3],
  ['Speak with Dead', 'speak-with-dead', 3],
  ['Speak with Plants', 'speak-with-plants', 3],
  ['Spellfire Flare', 'spellfire-flare', 2],
  ['Spellfire Storm', 'spellfire-storm', 2],
  ['Spider Climb', 'spider-climb', 3],
  ['Spike Growth', 'spike-growth', 3],
  ['Spirit Guardians', 'spirit-guardians', 3],
  ['Spirit Lantern', 'spirit-lantern', 2],
  ['Spirit Of Death', 'spirit-of-death', 1],
  ['Spirit Shroud', 'spirit-shroud', 1],
  ['Spiritual Weapon', 'spiritual-weapon', 3],
  ['Spray Of Cards', 'spray-of-cards', 1],
  ['Staggering Smite', 'staggering-smite', 3],
  ['Starry Wisp', 'starry-wisp', 2],
  ['Steel Wind Strike', 'steel-wind-strike', 3],
  ['Sticks to Snakes', 'sticks-to-snakes', 2],
  ['Stinking Cloud', 'stinking-cloud', 3],
  ['Stone Shape', 'stone-shape', 3],
  ['Stoneskin', 'stoneskin', 3],
  ['Storm of Vengeance', 'storm-of-vengeance', 3],
  ['Storm Sphere', 'storm-sphere', 1],
  ['Summon Aberration', 'summon-aberration', 3],
  ['Summon Beast', 'summon-beast', 3],
  ['Summon Celestial', 'summon-celestial', 3],
  ['Summon Construct', 'summon-construct', 3],
  ['Summon Dinosaur', 'summon-dinosaur', 2],
  ['Summon Draconic Spirit', 'summon-draconic-spirit', 1],
  ['Summon Dragon', 'summon-dragon', 2],
  ['Summon Elemental', 'summon-elemental', 3],
  ['Summon Fey', 'summon-fey', 3],
  ['Summon Fiend', 'summon-fiend', 3],
  ['Summon Greater Demon', 'summon-greater-demon', 1],
  ['Summon Lesser Demons', 'summon-lesser-demons', 1],
  ['Summon Plant', 'summon-plant', 2],
  ['Summon Shadowspawn', 'summon-shadowspawn', 1],
  ['Summon Undead', 'summon-undead', 3],
  ['Sunbeam', 'sunbeam', 3],
  ['Sunburst', 'sunburst', 3],
  ['Swift Quiver', 'swift-quiver', 3],
  ['Sword Burst', 'sword-burst', 1],
  ['Sylune\'s Viper', 'sylune-s-viper', 2],
  ['Synaptic Static', 'synaptic-static', 3],
  ['Tasha\'s Bubbling Cauldron', 'tasha-s-bubbling-cauldron', 2],
  ['Tasha\'s Caustic Brew', 'tashas-caustic-brew', 1],
  ['Tasha\'s Hideous Laughter', 'tashas-hideous-laughter', 1],
  ['Tasha\'s Hideous Laughter', 'tasha-s-hideous-laughter', 2],
  ['Tasha\'s Mind Whip', 'tashas-mind-whip', 1],
  ['Tasha\'s Otherworldly Guise', 'tashas-otherworldly-guise', 1],
  ['Telekinesis', 'telekinesis', 3],
  ['Teleportation Circle', 'teleportation-circle', 3],
  ['Temple of the Gods', 'temple-of-the-gods', 1],
  ['Temporal Shunt', 'temporal-shunt', 1],
  ['Tenser\'s Floating Disk', 'tensers-floating-disk', 1],
  ['Tenser\'s Floating Disk', 'tenser-s-floating-disk', 2],
  ['Tenser\'s Transformation', 'tensers-transformation', 1],
  ['Tether Essence', 'tether-essence', 1],
  ['Thaumaturgy', 'thaumaturgy', 3],
  ['Thorn Whip', 'thorn-whip', 3],
  ['Thunder Step', 'thunder-step', 1],
  ['Thunderclap', 'thunderclap', 3],
  ['Thunderous Smite', 'thunderous-smite', 3],
  ['Thunderwave', 'thunderwave', 3],
  ['Tidal Wave', 'tidal-wave', 1],
  ['Time Ravage', 'time-ravage', 1],
  ['Time Stop', 'time-stop', 3],
  ['Tiny Servant', 'tiny-servant', 1],
  ['Toll the Dead', 'toll-the-dead', 3],
  ['Tortoise Shell', 'tortoise-shell', 2],
  ['Transmute Rock', 'transmute-rock', 1],
  ['Transport via Plants', 'transport-via-plants', 3],
  ['Tree Stride', 'tree-stride', 3],
  ['True Polymorph', 'true-polymorph', 3],
  ['True Resurrection', 'true-resurrection', 3],
  ['True Seeing', 'true-seeing', 3],
  ['True Strike', 'true-strike', 3],
  ['Uncertain Footing', 'uncertain-footing', 2],
  ['Unseen Servant', 'unseen-servant', 3],
  ['Vampiric Touch', 'vampiric-touch', 3],
  ['Vicious Mockery', 'vicious-mockery', 3],
  ['Vision of Elapsing Eons', 'vision-of-elapsing-eons', 2],
  ['Vitriolic Sphere', 'vitriolic-sphere', 3],
  ['Void Star', 'void-star', 2],
  ['Vortex Warp', 'vortex-warp', 1],
  ['Wail of the Banshee', 'wail-of-the-banshee', 2],
  ['Wall of Fire', 'wall-of-fire', 3],
  ['Wall of Force', 'wall-of-force', 3],
  ['Wall of Ice', 'wall-of-ice', 3],
  ['Wall of Light', 'wall-of-light', 1],
  ['Wall of Sand', 'wall-of-sand', 1],
  ['Wall of Stone', 'wall-of-stone', 3],
  ['Wall of Thorns', 'wall-of-thorns', 3],
  ['Wall of Water', 'wall-of-water', 1],
  ['Wardaway', 'wardaway', 2],
  ['Warding Bond', 'warding-bond', 3],
  ['Warding Wind', 'warding-wind', 1],
  ['Warp Sense', 'warp-sense', 1],
  ['Water Breathing', 'water-breathing', 3],
  ['Water Walk', 'water-walk', 3],
  ['Watery Sphere', 'watery-sphere', 1],
  ['Waves of Exhaustion', 'waves-of-exhaustion', 2],
  ['Wind Walk', 'wind-walk', 3],
  ['Wind Wall', 'wind-wall', 3],
  ['Witch Bolt', 'witch-bolt', 3],
  ['Wither and Bloom', 'wither-and-bloom', 3],
  ['Word of Radiance', 'word-of-radiance', 3],
  ['Word of Recall', 'word-of-recall', 3],
  ['Wrath Of Nature', 'wrath-of-nature', 1],
  ['Wrathful Smite', 'wrathful-smite', 3],
  ['Wristpocket', 'wristpocket', 1],
  ['Yolande\'s Regal Presence', 'yolande-s-regal-presence', 2],
  ['Zephyr Strike', 'zephyr-strike', 1],
  ['Zone of Amicability', 'zone-of-amicability', 2],
  ['Zone of Truth', 'zone-of-truth', 3],
];

export const EDITIONS = {
  // HTTPS, deliberately, for both.
  //
  // dnd2024.wikidot.com answers a 301 from https to http — it has no working
  // certificate — so a reader following one of these ends up on plain HTTP
  // whatever we write. Writing https is us asking for the secure one and the
  // site refusing, rather than us choosing the insecure one; and the day they
  // fix it, these links are already right.
  '2014': { label: '2014 rules', base: 'https://dnd5e.wikidot.com/', bit: 1 },
  '2024': { label: '2024 rules', base: 'https://dnd2024.wikidot.com/', bit: 2 },
};

export const DEFAULT_EDITION = '2024';

export const isEdition = (e) => Object.hasOwn(EDITIONS, String(e ?? ''));

// The spells a given edition can actually answer for, as { name, url }.
//
// Built per edition rather than filtered per lookup, because the dashboard asks
// once and matches every name in a write-up against the answer.
export function rulesFor(edition = DEFAULT_EDITION) {
  const ed = EDITIONS[isEdition(edition) ? edition : DEFAULT_EDITION];
  return SPELLS
    .filter(([, , on]) => on & ed.bit)
    .map(([name, slug]) => ({ name, url: `${ed.base}spell:${slug}` }));
}

export const SPELL_COUNT = SPELLS.length;
