// Whimsical, randomly-cycled flavor text for everything the bot says in
// Discord. Each category has ~20 variants so the bot doesn't sound like a
// robot reading the same line every session. pick() just grabs a random one
// and fills in {placeholders} — nothing fancier than that is needed here.

function fmt(template, vars) {
  return template.replace(/\{(\w+)\}/g, (_, key) => (vars[key] ?? ''));
}

export function pick(list, vars = {}) {
  const template = list[Math.floor(Math.random() * list.length)];
  return fmt(template, vars);
}

export const JOIN_NO_CHANNEL = [
  "🧙 I can't record a voice channel you're not in. Join one first.",
  '🕯️ The scribe needs a room to sit in — hop into a voice channel first.',
  "🐦 A familiar can't follow you if you're nowhere to be found. Join a voice channel first.",
  '📜 There is no scene to record — join a voice channel first.',
  '🗝️ The archive requires a location. Join a voice channel, then try again.',
  "🧝 I'd love to eavesdrop, but you'll need to be in a voice channel first.",
  "🔮 The crystal ball shows... nothing. You're not in a voice channel.",
  '🪶 The quill has nothing to write about — join a voice channel first.',
  "🕰️ History can't be made from an empty room. Join a voice channel first.",
  '📯 The herald has no one to announce — join a voice channel first.',
  "🐉 Even I can't record silence from the void. Join a voice channel first.",
  '📖 This chapter needs a setting — join a voice channel to begin.',
  '🌙 No session brews here. Join a voice channel first.',
  '⚗️ Nothing to distill yet — join a voice channel first.',
  '🕸️ No threads to weave — you need to be in a voice channel first.',
  '🧾 The ledger stays blank until you join a voice channel.',
  "🧠 I can't recall what I never heard — join a voice channel first.",
  "🎙️ Microphone's pointed at an empty room. Join a voice channel first.",
  '🗿 Even ancient stones need a room to echo in. Join a voice channel first.',
  '🧙‍♂️ Step into a voice channel, and the recording shall follow.',
];

export const JOIN_ALREADY_RECORDING = [
  "🧙 I'm already scribbling away in this server — one session at a time.",
  '📜 The quill is already moving. Already recording in this server.',
  "🕯️ The candle's already lit — I'm already recording here.",
  "🐦 The familiar's already perched and listening. Already recording in this server.",
  '🔮 The crystal ball is already watching this server.',
  "🗝️ The tome's already open — already recording in this server.",
  "🧾 One scroll at a time — I'm already recording this server.",
  '📖 This chapter is already being written. Already recording here.',
  '🌙 The night is already being chronicled in this server.',
  "⚗️ Already distilling this session — can't start a second brew.",
  "🕸️ Already weaving this session's threads — one tapestry at a time.",
  "🧠 I'm already listening in this server, no need to ask twice.",
  '🎙️ Already rolling in this server — no double recordings.',
  "🐉 One dragon, one ledger — I'm already recording here.",
  '🗿 The stones are already echoing this session.',
  '📯 The herald is already on duty in this server.',
  "🧝 Already chronicling this one — can't split my attention across two.",
  "🕰️ Time's already being kept in this server. Already recording.",
  "🪶 The quill's already dancing — already recording in this server.",
  '⛩️ One shrine, one scribe — already recording here.',
];

export const JOIN_STARTED = [
  '🧙 A hooded scribe slips into **{channel}**, quill already scratching against parchment.',
  '📜 The court recorder has entered **{channel}** — speak clearly, adventurers.',
  '🕯️ A spectral quill begins hovering over fresh parchment in **{channel}**.',
  '🐉 The dragon in the corner of **{channel}** cracks open a ledger and starts writing.',
  '🧝 An elven chronicler tucks into **{channel}**, ready to immortalise your legend.',
  '📖 The Tome of Record creaks open in **{channel}**. Every word from here is history.',
  '🕰️ Time itself pauses to listen — recording begins in **{channel}**.',
  '🪶 A raven lands in **{channel}**, quill in beak, ready to transcribe your deeds.',
  '🔮 The crystal ball in **{channel}** flickers to life, watching, listening, recording.',
  "🧙‍♂️ 'Ahem. Testing, testing.' The wizard's notes begin in **{channel}**.",
  '📯 A herald announces: the chronicles of **{channel}** begin now.',
  '🕯️ Candles flicker as the Keeper of Records settles into **{channel}**.',
  '🗝️ A hidden archivist unlocks their notebook in **{channel}**. Let the tale begin.',
  '🐦 A tiny familiar perches nearby, taking down every word spoken in **{channel}**.',
  '📚 The Library of This Very Session opens a new chapter in **{channel}**.',
  '🕸️ Threads of fate are being woven into ink — recording started in **{channel}**.',
  "🧾 The guild scribe unrolls a fresh scroll in **{channel}**. Don't waste it on small talk.",
  "🌙 Under a watchful moon, tonight's tale begins recording in **{channel}**.",
  '⚗️ A memory-bottling ritual begins in **{channel}** — every word, preserved.',
  '🎙️ Recording started in **{channel}**. The scribe is listening, and so is history.',
];

export const LEAVE_NOT_RECORDING = [
  "🧙 There's nothing to stop — I'm not currently recording here.",
  "📜 The quill's already still. Not currently recording.",
  "🕯️ No candle burning here — I'm not recording this server right now.",
  "🐦 The familiar flew off ages ago. Not currently recording.",
  '🔮 The crystal ball is dark. Not currently recording.',
  "🗝️ There's no open tome to close — not currently recording.",
  '🧾 No scroll in progress — not currently recording.',
  '📖 No chapter is being written right now. Not currently recording.',
  "🌙 Quiet night — I'm not recording anything here.",
  "⚗️ Nothing's brewing — not currently recording.",
  "🕸️ No threads being woven right now — not currently recording.",
  "🧠 I've nothing queued in memory — not currently recording.",
  "🎙️ Nothing's rolling — not currently recording.",
  "🐉 The ledger's shut — I'm not recording this server.",
  '🗿 Silent stones — not currently recording.',
  '📯 No herald on duty — not currently recording.',
  "🧝 I've already wandered off — not currently recording here.",
  "🕰️ No time being kept right now — not currently recording.",
  '🪶 The quill is resting — not currently recording.',
  '⛩️ The shrine is empty — not currently recording.',
];

export const LEAVE_START = [
  '⏳ The scribe closes the tome and begins the long work of transcription...',
  '🖋️ Setting down the quill... now deciphering the chaos of tonight\'s session.',
  '📜 Rolling up the scroll. Give the scribe a moment to make sense of it all.',
  "🧙 'One moment...' the wizard mutters, flipping back through pages of notes.",
  '🕯️ The candle gutters as the archivist begins sorting tonight\'s events into order.',
  '🔍 Poring over every word spoken tonight — this may take a while...',
  "🪄 A minor divination is cast to untangle who said what, and when.",
  '📖 Closing the Tome of Record... transcription is underway.',
  "🧾 The guild scribe grumbles about everyone talking over each other and starts transcribing.",
  '🕰️ Turning back the hourglass to relive every moment of the session...',
  '🐦 The familiar flies off to the archive with tonight\'s notes in tow.',
  "🧠 Recalling every word with unnerving precision — please stand by.",
  "⚗️ Distilling tonight's chaos into something readable. Patience, adventurer.",
  '📚 Filing tonight\'s chapter into the grand campaign archive...',
  "🕸️ Untangling the threads of conversation into a coherent record.",
  '🪶 The raven returns to its perch to begin the tedious work of transcription.',
  '🗝️ Locking away tonight\'s secrets... transcription in progress.',
  '🌒 As the session ends, the ink begins to dry into legible history.',
  "🔮 The crystal ball replays tonight's events, frame by frame, word by word.",
  '⏳ Stopping and transcribing — this can take a while for a long session...',
];

// {failCount}
export const LEAVE_NOTHING_USABLE = [
  '😶 Nothing but silence and static came through — {failCount} clip(s) failed to transcribe.',
  "🕸️ The scribe's notes came back blank. {failCount} recording(s) couldn't be read.",
  '📜 An empty scroll — transcription produced nothing usable ({failCount} failure(s)).',
  "🧙 'I... didn't catch any of that.' Transcription failed on {failCount} clip(s).",
  "🔇 The session was recorded, but the words didn't survive the journey ({failCount} failure(s)).",
  '🗝️ The vault opened onto an empty room — {failCount} clip(s) failed to transcribe.',
  '🐦 The familiar came back with nothing but scribbles ({failCount} failure(s)).',
  '📖 A blank page where a chapter should be — {failCount} clip(s) unreadable.',
  "🧾 The scroll came back smudged beyond reading ({failCount} failure(s)).",
  '🕯️ The candle burned out before the words could be caught ({failCount} failure(s)).',
  '🔮 The crystal ball only showed static — {failCount} clip(s) failed to transcribe.',
  '🌙 The night kept its secrets — {failCount} clip(s) came back unusable.',
  "⚗️ The distillation failed — nothing usable came through ({failCount} failure(s)).",
  '🕰️ Time swallowed those words whole — {failCount} clip(s) unreadable.',
  '🪶 The quill snapped mid-sentence — {failCount} clip(s) failed to transcribe.',
  "🧠 My memory of that session is a blank — {failCount} clip(s) unusable.",
  '🐉 Even the dragon shrugged — {failCount} clip(s) came through unreadable.',
  '🗿 The stones stayed silent — {failCount} clip(s) failed to transcribe.',
  '📯 The herald has nothing to announce — {failCount} clip(s) unusable.',
  '😶 Transcription produced nothing usable ({failCount} failure(s)).',
];

// {count}
export const LEAVE_SUMMARIZING_NOW = [
  '✅ {count} lines transcribed. The wizard on the other side of the LAN is drafting your recap now.',
  '✅ {count} lines captured for posterity. Summoning the summary as we speak.',
  '✅ Transcribed {count} lines. A more learned mind is now distilling it into a proper recap.',
  '✅ {count} lines of glory (and rambling) recorded. Summarising now.',
  '✅ {count} lines saved to the annals. The recap-conjuring begins immediately.',
  "✅ {count} lines transcribed — handing this off to the Oracle for summarising.",
  '✅ Captured {count} lines of dialogue. Weaving them into a recap now.',
  "✅ {count} lines down. The scribe's apprentice (your PC) is writing the summary.",
  '✅ Transcription complete — {count} lines. Recap incoming shortly.',
  '✅ {count} lines of session recorded. The summary spell is already being cast.',
  '✅ {count} lines transcribed. Turning chaos into a coherent recap now...',
  '✅ {count} lines saved. Your friendly neighbourhood AI is drafting the recap.',
  '✅ {count} lines of transcript ready. Summarising on your PC as we speak.',
  '✅ {count} lines archived. A recap is being conjured on your machine now.',
  '✅ {count} lines transcribed successfully. Recap generation underway.',
  '✅ {count} lines of session lore captured. Summarising now, stand by.',
  '✅ Transcribed {count} lines — the Ollama oracle is already at work.',
  '✅ {count} lines recorded for the ages. Summary coming right up.',
  '✅ {count} lines transcribed. The tale is being polished into a recap now.',
  '✅ Transcribed {count} lines. Summarising now on your PC...',
];

// {count}, {meetingId}
export const LEAVE_SUMMARY_QUEUED = [
  "✅ {count} lines transcribed, but your PC seems to be off adventuring elsewhere. The recap is queued — or run `/summarise meeting_id:{meetingId}` once it's back.",
  '✅ {count} lines captured. Alas, the Oracle (your PC) is unreachable. It\'ll retry automatically, or use `/summarise meeting_id:{meetingId}`.',
  "✅ {count} lines transcribed. Your PC is either sleeping or elsewhere — the summary will wait patiently in the queue.",
  "✅ Transcription done ({count} lines) — but the summarising wizard's tower (your PC) is dark. It's queued for when the lights come back on.",
  "✅ {count} lines recorded. The recap-conjuring machine appears to be powered down; I'll keep trying.",
  '✅ {count} lines saved. Your PC\'s Ollama isn\'t answering — queued for automatic retry, or `/summarise meeting_id:{meetingId}` manually.',
  "✅ {count} lines transcribed. No answer from the Oracle's tower — it's queued until your PC returns.",
  '✅ {count} lines of dialogue captured. The summary awaits your PC waking up.',
  '✅ {count} lines down. Your PC seems to be resting — the recap will follow once it stirs.',
  "✅ {count} lines transcribed successfully, but the Ollama spirit isn't home. Queued for later.",
  "✅ {count} lines recorded. Summoning failed — your PC isn't reachable. It'll auto-retry.",
  "✅ {count} lines transcribed. The recap-scribe's workshop (your PC) is closed for now — queued.",
  '✅ {count} lines saved to the archive. Recap pending — your PC needs to be turned on.',
  '✅ {count} lines of transcript ready, but no reply from the LAN oracle. Retrying automatically.',
  "✅ {count} lines transcribed. It seems your PC has wandered off — the summary awaits its return.",
  "✅ {count} lines captured. Recap queued; your PC's Ollama isn't reachable right now.",
  '✅ {count} lines transcribed. The AI scribe is currently offline — try `/summarise meeting_id:{meetingId}` later.',
  '✅ {count} lines recorded for the ages. Summary delayed — the PC oracle sleeps.',
  '✅ {count} lines transcribed. Waiting on your PC to come back online for the recap.',
  "✅ Transcribed {count} lines. Your PC's Ollama isn't reachable right now — the summary is queued and will run automatically once it's back, or run `/summarise meeting_id:{meetingId}` after you turn it on.",
];

export const HISTORY_EMPTY = [
  '📭 The archive is bare — no sessions recorded yet.',
  "📜 An empty shelf — nothing's been recorded yet.",
  '🗝️ The vault has nothing in it yet. No sessions recorded.',
  '🧾 The ledger has yet to be opened. No sessions recorded yet.',
  "📖 This campaign's first chapter hasn't been written yet.",
  '🕯️ No candles have been lit for a session yet.',
  '🐦 The familiar has nothing to report — no sessions yet.',
  "🔮 The crystal ball shows nothing — no history to speak of yet.",
  '🧙 Not a single tale has been told yet. No sessions recorded.',
  '🌙 No nights have been chronicled yet.',
  "⚗️ Nothing's been distilled into history yet.",
  '🕸️ No threads have been woven into this archive yet.',
  '🧠 My memory is blank — no sessions recorded yet.',
  '🎙️ Nothing on the tape yet — no sessions recorded.',
  '🐉 The dragon\'s hoard of stories is empty so far.',
  '🗿 The stones have nothing carved into them yet.',
  '📯 No proclamations to make — no sessions yet.',
  "🧝 The chronicle begins with you — no sessions recorded yet.",
  '🕰️ Time has yet to record anything here.',
  '📭 No sessions recorded yet.',
];

// {url}
export const SUMMARIZE_UNREACHABLE = [
  "🔮 The Oracle's tower is dark — Ollama still isn't reachable at {url}. It'll retry automatically too.",
  "🧙 Still no answer from your PC's Ollama at {url}. It'll retry in the background.",
  '📡 Signal lost to {url} — the summarising wizard is still unreachable, but retries continue quietly.',
  "🕯️ Knocked on your PC's door at {url} — no one home yet. Auto-retry is still running.",
  "🐦 The familiar returned empty-winged from {url} — still unreachable. It'll keep trying.",
  "⚗️ The distillation machine at {url} is still cold. Background retries continue.",
  "🗝️ Still can't reach the Oracle's chamber at {url}. Retrying automatically.",
  'Your PC\'s Ollama still isn\'t reachable at {url}. It\'ll retry automatically in the background too.',
  "🧾 No reply from {url} yet — the queue will keep knocking.",
  '🌙 The tower at {url} sleeps on. Background retries continue.',
  "🕰️ Still waiting on {url} to answer. Retrying automatically in the meantime.",
  '📖 That chapter awaits a working {url} — still unreachable, retrying quietly.',
  "🧠 My connection to {url} remains silent. Auto-retry continues.",
  '🐉 The dragon at {url} is still asleep. Retries continue in the background.',
  '🗿 No echo back from {url} yet. Background retries continue.',
  '📯 No herald could reach {url} — still unreachable, retrying automatically.',
  "🧝 The messenger sent to {url} hasn't returned. Retrying automatically.",
  '⛩️ The shrine at {url} remains dark. Auto-retry continues quietly.',
  "🪶 Still no word back from {url}. It'll retry automatically too.",
  "Your PC's Ollama still isn't reachable at {url}. It'll retry automatically in the background too.",
];

// {meetingId}
export const SUMMARIZE_QUEUED = [
  '🔮 Queued meeting #{meetingId} for an immediate retry — check back shortly.',
  '🧙 Meeting #{meetingId} has been shoved to the front of the queue. Check back shortly.',
  '📜 Meeting #{meetingId} is up next for summarising — check back shortly.',
  "⚗️ Re-distilling meeting #{meetingId} right now — check back shortly.",
  '🕯️ Meeting #{meetingId} moves to the top of the pile. Check back shortly.',
  '🐦 The familiar has been sent to fetch a summary for meeting #{meetingId}. Check back shortly.',
  '🗝️ Meeting #{meetingId} queued for immediate retry — check back shortly.',
  '🧾 Meeting #{meetingId} is next on the scribe\'s desk. Check back shortly.',
  '📖 Reopening meeting #{meetingId} for a fresh summary attempt. Check back shortly.',
  '🌙 Meeting #{meetingId} gets another chance tonight — check back shortly.',
  '🕰️ Meeting #{meetingId} bumped up the queue. Check back shortly.',
  '🧠 Recalling meeting #{meetingId} once more — check back shortly.',
  '🎙️ Re-queued meeting #{meetingId} for summarising — check back shortly.',
  '🐉 Meeting #{meetingId} goes back into the furnace for another attempt.',
  '🗿 Meeting #{meetingId} carved back into the queue. Check back shortly.',
  '📯 Meeting #{meetingId} announced for another summarising attempt.',
  '🧝 Meeting #{meetingId} handed back to the chronicler. Check back shortly.',
  '⛩️ Meeting #{meetingId} placed back on the altar for summarising.',
  '🪶 Meeting #{meetingId} queued once more — check back shortly.',
  'Queued meeting #{meetingId} for immediate retry — check back shortly.',
];

// {meetingId}, {channel}, {date}
export const EXPORT_INTRO = [
  "📜 Here's the full transcript for meeting #{meetingId} ({channel}, {date}).",
  "🗝️ Unsealing the archive for meeting #{meetingId} ({channel}, {date}).",
  '📖 Pulling meeting #{meetingId} ({channel}, {date}) off the shelf for you.',
  "🧾 The scroll for meeting #{meetingId} ({channel}, {date}), delivered.",
  "🕯️ Dusting off the record of meeting #{meetingId} ({channel}, {date}).",
  '🐦 The familiar fetches the transcript for meeting #{meetingId} ({channel}, {date}).',
  "🔮 Replaying meeting #{meetingId} ({channel}, {date}) from the archive.",
  '🧙 Here is what was said in meeting #{meetingId} ({channel}, {date}).',
  "🌙 The record of that night — meeting #{meetingId} ({channel}, {date}).",
  '⚗️ The distilled transcript of meeting #{meetingId} ({channel}, {date}).',
  '🕰️ Turning back the clock to meeting #{meetingId} ({channel}, {date}).',
  '🧠 Everything recalled from meeting #{meetingId} ({channel}, {date}).',
  '🎙️ The full tape of meeting #{meetingId} ({channel}, {date}).',
  '🐉 The hoard yields the transcript for meeting #{meetingId} ({channel}, {date}).',
  '🗿 Carved in full: meeting #{meetingId} ({channel}, {date}).',
  '📯 Announcing the transcript for meeting #{meetingId} ({channel}, {date}).',
  '🧝 The chronicle of meeting #{meetingId} ({channel}, {date}), retrieved.',
  '⛩️ Retrieved from the shrine: meeting #{meetingId} ({channel}, {date}).',
  '🪶 The full quill-work of meeting #{meetingId} ({channel}, {date}).',
  "Transcript for meeting #{meetingId} ({channel}, {date}).",
];

// {name}
export const SETCHARACTER_CONFIRM = [
  "🧙 Noted — you'll appear as **{name}** in every transcript and recap from now on.",
  "📜 Your true name has been inscribed: **{name}**. That's how you'll show up from now on.",
  "🗝️ The archive now knows you as **{name}**.",
  "🧾 Recorded in the ledger: you are **{name}** henceforth.",
  "🕯️ By candlelight, your name is set: **{name}**.",
  "🐦 The familiar will now call you **{name}** in every record.",
  "🔮 The crystal ball now sees you as **{name}**.",
  "🧝 From this session on, you're known in the chronicles as **{name}**.",
  "🌙 Under this name you shall be remembered: **{name}**.",
  "⚗️ Distilled down to one true name: **{name}**.",
  "🕰️ History will record you as **{name}** from here on.",
  "🧠 Committed to memory: you are **{name}**.",
  "🎙️ On record: you're **{name}** from now on.",
  "🐉 Even the dragon will note you as **{name}** going forward.",
  "🗿 Carved into the stone: **{name}**.",
  "📯 Let it be announced: you are **{name}**.",
  "⛩️ The shrine accepts your name: **{name}**.",
  "🪶 Inked in for good: **{name}**.",
  "🧙‍♂️ Got it — you'll show up as **{name}** in transcripts and notes from now on.",
  "Got it — you'll show up as **{name}** in transcripts and notes from now on.",
];

// {reachable}
export const STATUS_IDLE = [
  "😴 Nothing queued for summarising right now. Your PC's Ollama is currently {reachable}.",
  "🧙 All caught up — nothing waiting to be summarised. Ollama is currently {reachable}.",
  "📜 The desk is clear — no sessions queued. Ollama is currently {reachable}.",
  '🕯️ Nothing left to distill right now. Ollama is currently {reachable}.',
  '🗝️ The queue is empty. Ollama is currently {reachable}.',
  '🐦 No errands for the familiar right now. Ollama is currently {reachable}.',
  '🔮 The crystal ball shows an empty queue. Ollama is currently {reachable}.',
  '🧾 Nothing pending in the ledger. Ollama is currently {reachable}.',
  '🌙 A quiet night — nothing queued. Ollama is currently {reachable}.',
  "⚗️ Nothing's brewing right now. Ollama is currently {reachable}.",
  '🕰️ No time being spent waiting right now. Ollama is currently {reachable}.',
  '🧠 Nothing on my mind right now. Ollama is currently {reachable}.',
  '🎙️ Nothing queued. Ollama is currently {reachable}.',
  "🐉 The dragon's ledger is empty for now. Ollama is currently {reachable}.",
  '🗿 No inscriptions pending. Ollama is currently {reachable}.',
  '📯 Nothing to announce right now. Ollama is currently {reachable}.',
  '🧝 All quiet on the chronicle front. Ollama is currently {reachable}.',
  '⛩️ The altar is clear. Ollama is currently {reachable}.',
  '🪶 The quill rests idle. Ollama is currently {reachable}.',
  "No sessions currently queued for summarisation. Your PC's Ollama is currently {reachable}.",
];

// {reachable}
export const STATUS_QUEUED_HEADER = [
  "🔮 Your PC's Ollama is currently {reachable}.\n\n**Queued:**",
  "🧙 Ollama is currently {reachable}. Here's what's waiting:\n\n**Queued:**",
  "📜 Ollama is currently {reachable}. The queue so far:\n\n**Queued:**",
  "🕯️ Ollama status: {reachable}.\n\n**Queued:**",
  "🗝️ Ollama is currently {reachable}. Waiting in the vault:\n\n**Queued:**",
  "🐦 Ollama is currently {reachable}. Errands pending:\n\n**Queued:**",
  "🧾 Ollama is currently {reachable}. On the ledger:\n\n**Queued:**",
  "🌙 Ollama is currently {reachable}. Still to be told:\n\n**Queued:**",
  "⚗️ Ollama is currently {reachable}. Still brewing:\n\n**Queued:**",
  "🕰️ Ollama is currently {reachable}. Waiting on time:\n\n**Queued:**",
  "🧠 Ollama is currently {reachable}. On my mind:\n\n**Queued:**",
  "🎙️ Ollama is currently {reachable}. On the tape, unsummarised:\n\n**Queued:**",
  "🐉 Ollama is currently {reachable}. In the dragon's ledger:\n\n**Queued:**",
  "🗿 Ollama is currently {reachable}. Awaiting inscription:\n\n**Queued:**",
  "📯 Ollama is currently {reachable}. To be announced:\n\n**Queued:**",
  "🧝 Ollama is currently {reachable}. Awaiting the chronicler:\n\n**Queued:**",
  "⛩️ Ollama is currently {reachable}. Upon the altar:\n\n**Queued:**",
  "🪶 Ollama is currently {reachable}. Awaiting ink:\n\n**Queued:**",
  "🔮 Your PC's Ollama is currently {reachable}.\n\n**Queued:**",
  "Your PC's Ollama is currently {reachable}.\n\n**Queued:**",
];

export const RECAP_NONE = [
  '📭 No completed sessions yet — nothing to recap.',
  "📜 The chronicle hasn't its first finished chapter yet.",
  '🗝️ The vault holds no finished tales yet.',
  '🧾 No completed sessions in the ledger yet.',
  "🕯️ No candle has burned through a full recap yet.",
  '🐦 The familiar has nothing finished to recite yet.',
  '🔮 The crystal ball shows no completed sessions yet.',
  '🧙 No recap exists yet — the tale is still being written.',
  '🌙 No night has reached its recap yet.',
  "⚗️ Nothing's been fully distilled into a recap yet.",
  '🕰️ History has no finished chapter to recall yet.',
  '🧠 My memory holds no completed recaps yet.',
  '🎙️ Nothing finished on the tape yet.',
  "🐉 The dragon's hoard has no finished tales yet.",
  '🗿 No stone bears a finished recap yet.',
  '📯 Nothing to proclaim yet — no completed sessions.',
  '🧝 The chronicler awaits a finished tale.',
  '⛩️ The shrine holds no completed recap yet.',
  '🪶 No ink has dried on a finished recap yet.',
  'No completed sessions yet.',
];

// {channel}, {date}
export const RECAP_HEADER = [
  '📜 **Recap — {channel} ({date})**',
  '🧙 **The Tale So Far — {channel} ({date})**',
  '🗝️ **From the Archive — {channel} ({date})**',
  '🕯️ **By Candlelight — {channel} ({date})**',
  '🐦 **As the Familiar Recalls — {channel} ({date})**',
  '🔮 **The Crystal Ball Remembers — {channel} ({date})**',
  '🌙 **Last We Left Off — {channel} ({date})**',
  '⚗️ **Distilled Memory — {channel} ({date})**',
  '🕰️ **A Look Back — {channel} ({date})**',
  '🧠 **What I Remember — {channel} ({date})**',
  '🎙️ **Previously, on {channel} ({date})**',
  '🐉 **From the Hoard — {channel} ({date})**',
  '🗿 **Carved in Stone — {channel} ({date})**',
  '📯 **Hear Ye — {channel} ({date})**',
  '🧝 **The Chronicler Speaks — {channel} ({date})**',
  '⛩️ **From the Shrine — {channel} ({date})**',
  '🪶 **Ink Still Fresh — {channel} ({date})**',
  '📖 **Last Chapter — {channel} ({date})**',
  '🧾 **On the Ledger — {channel} ({date})**',
  '📜 **Recap — {channel} ({date})**',
];

// {channel}, {date}
export const POST_SESSION_HEADER = [
  '# 🐉 Session Recap — {channel} ({date})',
  '# 🧙 The Wizard\'s Notes — {channel} ({date})',
  '# 📜 Chronicle Entry — {channel} ({date})',
  '# 🕯️ By Candlelight — {channel} ({date})',
  '# 🗝️ From the Archive — {channel} ({date})',
  '# 🐦 The Familiar Reports — {channel} ({date})',
  '# 🔮 The Crystal Ball Recalls — {channel} ({date})',
  '# 🌙 Last Night\'s Tale — {channel} ({date})',
  '# ⚗️ Distilled Memories — {channel} ({date})',
  '# 🕰️ A Look Back — {channel} ({date})',
  '# 🧠 What Was Remembered — {channel} ({date})',
  '# 🎙️ Previously... — {channel} ({date})',
  '# 🗿 Carved in Stone — {channel} ({date})',
  '# 📯 Hear Ye, Hear Ye — {channel} ({date})',
  '# 🧝 The Chronicler\'s Account — {channel} ({date})',
  '# ⛩️ From the Shrine of Record — {channel} ({date})',
  '# 🪶 Fresh Ink — {channel} ({date})',
  '# 📖 Another Chapter Closes — {channel} ({date})',
  '# 🧾 The Guild Ledger — {channel} ({date})',
  '# 🐉 Session Recap — {channel} ({date})',
];

export const POST_SESSION_ATTACHMENT_CAPTION = [
  '📎 Full session markdown (transcript + notes) — drop into Obsidian:',
  '📎 The complete chronicle, ready for your Obsidian vault:',
  '📎 Everything that happened, in full — for Obsidian:',
  '📎 The unabridged record (transcript + notes), Obsidian-ready:',
  '📎 A copy for the archive — drop this into Obsidian:',
  '📎 The full scroll, transcript and all, for Obsidian:',
  '📎 Complete notes attached — Obsidian-ready as always:',
  '📎 The whole session, transcribed and summarised, for your vault:',
  '📎 Here\'s the full write-up (transcript + notes) for Obsidian:',
  '📎 Filed and ready — full session markdown for Obsidian:',
  '📎 The complete record, transcript included, Obsidian-ready:',
  '📎 Nothing left out — full markdown for your Obsidian vault:',
  '📎 The definitive account (transcript + notes) — Obsidian-ready:',
  '📎 Everything said and summarised, packaged for Obsidian:',
  '📎 The full session file, ready to drop into your vault:',
  '📎 Complete transcript + notes, Obsidian-formatted:',
  '📎 The whole record, start to finish, for Obsidian:',
  '📎 A full accounting of tonight, Obsidian-ready:',
  '📎 The archive copy — transcript and notes, for Obsidian:',
  '📎 Full session markdown (transcript + notes) — drop into Obsidian:',
];

export const FUNNY_NONE = [
  "🤷 Nothing funny on record yet — either you've all been very sensible, or nobody's cast Fireball indoors yet.",
  "😐 No memorable chaos recorded so far. Give it time.",
  '🧙 The scribe has yet to write down anything worth laughing about. A quiet campaign, so far.',
  "📜 The archive of foolishness is empty. Surely that won't last.",
  "🎭 No blooper reel yet — this campaign is being suspiciously well-behaved.",
  '🧾 Nothing filed under "chaos" yet.',
  "🕯️ Not a single recorded disaster yet. Impressive, honestly.",
  "🐦 The familiar hasn't overheard anything worth repeating yet.",
  '🔮 The crystal ball shows a distinct lack of tomfoolery so far.',
  "🌙 No embarrassing moments on the books yet.",
  "⚗️ Nothing chaotic enough to bottle yet.",
  "🕰️ History hasn't recorded a single blunder yet.",
  "🧠 I've got nothing funny filed away yet — ask again after a few more sessions.",
  "🎙️ Nothing on the blooper tape yet.",
  "🐉 Even the dragon hasn't seen anything worth laughing at yet.",
  '🗿 No moment has been carved into the "hall of shame" yet.',
  "📯 Nothing embarrassing enough to announce yet.",
  "🧝 The chronicler hasn't caught anyone doing anything silly yet.",
  "⛩️ The shrine of chaos stands empty, for now.",
  "🪶 Not a single funny quill-mark yet — give the party time.",
];

// {channel}, {date}, {moment}
export const FUNNY_HEADER = [
  '😂 Remember when, back in **{channel}** ({date})... {moment}',
  '🎭 A moment worth remembering, from **{channel}** ({date}):\n\n{moment}',
  '🧙 Pulled from the archive — **{channel}** ({date}):\n\n{moment}',
  '📜 Straight from the record books, **{channel}** ({date}):\n\n{moment}',
  '🐦 The familiar recalls, from **{channel}** ({date}):\n\n{moment}',
  '🔮 The crystal ball shows a memory from **{channel}** ({date}):\n\n{moment}',
  '🌙 A blast from the past — **{channel}** ({date}):\n\n{moment}',
  '⚗️ A distilled memory from **{channel}** ({date}):\n\n{moment}',
  '🕰️ Turning back the clock to **{channel}** ({date})...\n\n{moment}',
  '🧠 I remember this one — **{channel}** ({date}):\n\n{moment}',
  '🎙️ Pulled at random from the tape — **{channel}** ({date}):\n\n{moment}',
  '🐉 From the hoard of chaos, **{channel}** ({date}):\n\n{moment}',
  '🗿 Carved into the hall of shame — **{channel}** ({date}):\n\n{moment}',
  '📯 Hear ye — a moment from **{channel}** ({date}):\n\n{moment}',
  '🧝 The chronicler grins and recalls, from **{channel}** ({date}):\n\n{moment}',
  '⛩️ From the shrine of chaos, **{channel}** ({date}):\n\n{moment}',
  '🪶 A moment worth re-inking — **{channel}** ({date}):\n\n{moment}',
  '📖 Flipping back to **{channel}** ({date})...\n\n{moment}',
  '🧾 On record, from **{channel}** ({date}):\n\n{moment}',
  '😂 A random moment worth remembering — **{channel}** ({date}):\n\n{moment}',
];

export const GENERIC_ERROR = [
  '💥 The spell fizzled: {message}',
  '🧙 Something went wrong in the workshop: {message}',
  '📜 The ink spilled: {message}',
  '🕯️ The candle blew out mid-sentence: {message}',
  "⚗️ That brew didn't go as planned: {message}",
  '🐦 The familiar dropped the message: {message}',
  '🗝️ The lock jammed: {message}',
  '🧾 The scroll tore: {message}',
  '🌙 Something went bump in the dark: {message}',
  '🕰️ Time slipped: {message}',
  '🧠 My memory glitched: {message}',
  '🎙️ Static on the line: {message}',
  '🐉 Even the dragon stumbled: {message}',
  '🗿 The stone cracked: {message}',
  '📯 The herald tripped over their words: {message}',
  '🧝 The chronicler dropped their quill: {message}',
  '⛩️ The ritual faltered: {message}',
  '🪶 The quill snapped: {message}',
  '🔮 The crystal ball cracked: {message}',
  'Something went wrong: {message}',
];
