// Whimsical, randomly-cycled flavor text for everything the bot says in
// Discord. Each category has ~20 variants so the bot doesn't sound like a
// robot reading the same line every session. pick() just grabs a random one
// and fills in {placeholders} — nothing fancier than that is needed here.

function fmt(template, vars) {
  return template.replace(/\{(\w+)\}/g, (_, key) => (vars[key] ?? ''));
}

export function pick(list, vars = {}) {
  const template = list[Math.floor(Math.random() * list.length)];
  return fmt(template, vars);
}

export const JOIN_NO_CHANNEL = [
  "🧙 I can't record a voice channel you're not in. Join one first.",
  '🕯️ The scribe needs a room to sit in — hop into a voice channel first.',
  "🐦 A familiar can't follow you if you're nowhere to be found. Join a voice channel first.",
  '📜 There is no scene to record — join a voice channel first.',
  '🗝️ The archive requires a location. Join a voice channel, then try again.',
  "🧝 I'd love to eavesdrop, but you'll need to be in a voice channel first.",
  "🔮 The crystal ball shows... nothing. You're not in a voice channel.",
  '🪶 The quill has nothing to write about — join a voice channel first.',
  "🕰️ History can't be made from an empty room. Join a voice channel first.",
  '📯 The herald has no one to announce — join a voice channel first.',
  "🐉 Even I can't record silence from the void. Join a voice channel first.",
  '📖 This chapter needs a setting — join a voice channel to begin.',
  '🌙 No session brews here. Join a voice channel first.',
  '⚗️ Nothing to distill yet — join a voice channel first.',
  '🕸️ No threads to weave — you need to be in a voice channel first.',
  '🧾 The ledger stays blank until you join a voice channel.',
  "🧠 I can't recall what I never heard — join a voice channel first.",
  "🎙️ Microphone's pointed at an empty room. Join a voice channel first.",
  '🗿 Even ancient stones need a room to echo in. Join a voice channel first.',
  '🧙‍♂️ Step into a voice channel, and the recording shall follow.',
];

export const JOIN_ALREADY_RECORDING = [
  "🧙 I'm already scribbling away in this server — one session at a time.",
  '📜 The quill is already moving. Already recording in this server.',
  "🕯️ The candle's already lit — I'm already recording here.",
  "🐦 The familiar's already perched and listening. Already recording in this server.",
  '🔮 The crystal ball is already watching this server.',
  "🗝️ The tome's already open — already recording in this server.",
  "🧾 One scroll at a time — I'm already recording this server.",
  '📖 This chapter is already being written. Already recording here.',
  '🌙 The night is already being chronicled in this server.',
  "⚗️ Already distilling this session — can't start a second brew.",
  "🕸️ Already weaving this session's threads — one tapestry at a time.",
  "🧠 I'm already listening in this server, no need to ask twice.",
  '🎙️ Already rolling in this server — no double recordings.',
  "🐉 One dragon, one ledger — I'm already recording here.",
  '🗿 The stones are already echoing this session.',
  '📯 The herald is already on duty in this server.',
  "🧝 Already chronicling this one — can't split my attention across two.",
  "🕰️ Time's already being kept in this server. Already recording.",
  "🪶 The quill's already dancing — already recording in this server.",
  '⛩️ One shrine, one scribe — already recording here.',
];

export const JOIN_STARTED = [
  '🧙 A hooded scribe slips into **{channel}**, quill already scratching against parchment.',
  '📜 The court recorder has entered **{channel}** — speak clearly, adventurers.',
  '🕯️ A spectral quill begins hovering over fresh parchment in **{channel}**.',
  '🐉 The dragon in the corner of **{channel}** cracks open a ledger and starts writing.',
  '🧝 An elven chronicler tucks into **{channel}**, ready to immortalise your legend.',
  '📖 The Tome of Record creaks open in **{channel}**. Every word from here is history.',
  '🕰️ Time itself pauses to listen — recording begins in **{channel}**.',
  '🪶 A raven lands in **{channel}**, quill in beak, ready to transcribe your deeds.',
  '🔮 The crystal ball in **{channel}** flickers to life, watching, listening, recording.',
  "🧙‍♂️ 'Ahem. Testing, testing.' The wizard's notes begin in **{channel}**.",
  '📯 A herald announces: the chronicles of **{channel}** begin now.',
  '🕯️ Candles flicker as the Keeper of Records settles into **{channel}**.',
  '🗝️ A hidden archivist unlocks their notebook in **{channel}**. Let the tale begin.',
  '🐦 A tiny familiar perches nearby, taking down every word spoken in **{channel}**.',
  '📚 The Library of This Very Session opens a new chapter in **{channel}**.',
  '🕸️ Threads of fate are being woven into ink — recording started in **{channel}**.',
  "🧾 The guild scribe unrolls a fresh scroll in **{channel}**. Don't waste it on small talk.",
  "🌙 Under a watchful moon, tonight's tale begins recording in **{channel}**.",
  '⚗️ A memory-bottling ritual begins in **{channel}** — every word, preserved.',
  '🎙️ Recording started in **{channel}**. The scribe is listening, and so is history.',
];

export const LEAVE_NOT_RECORDING = [
  "🧙 There's nothing to stop — I'm not currently recording here.",
  "📜 The quill's already still. Not currently recording.",
  "🕯️ No candle burning here — I'm not recording this server right now.",
  "🐦 The familiar flew off ages ago. Not currently recording.",
  '🔮 The crystal ball is dark. Not currently recording.',
  "🗝️ There's no open tome to close — not currently recording.",
  '🧾 No scroll in progress — not currently recording.',
  '📖 No chapter is being written right now. Not currently recording.',
  "🌙 Quiet night — I'm not recording anything here.",
  "⚗️ Nothing's brewing — not currently recording.",
  "🕸️ No threads being woven right now — not currently recording.",
  "🧠 I've nothing queued in memory — not currently recording.",
  "🎙️ Nothing's rolling — not currently recording.",
  "🐉 The ledger's shut — I'm not recording this server.",
  '🗿 Silent stones — not currently recording.',
  '📯 No herald on duty — not currently recording.',
  "🧝 I've already wandered off — not currently recording here.",
  "🕰️ No time being kept right now — not currently recording.",
  '🪶 The quill is resting — not currently recording.',
  '⛩️ The shrine is empty — not currently recording.',
];

// /leave no longer transcribes — it stops recording and queues the session
// for later (see pipeline/transcribe-schedule.js). These used to say the
// scribe "begins the long work of transcription", which read fine when it was
// true and became a lie the moment transcription moved behind the schedule:
// the table would be told the work was underway while nothing was happening,
// possibly until Monday. So they now describe the tome being CLOSED and set
// aside, which is exactly what happened.
export const LEAVE_START = [
  '⏳ The scribe closes the tome and sets it aside for later.',
  '🖋️ Setting down the quill. Tonight\'s pages are safe until the archivist returns.',
  '📜 Rolling up the scroll and tying it off. It keeps.',
  "🧙 'Enough for tonight,' the wizard mutters, stacking the notes with care.",
  '🕯️ The candle is snuffed. Tonight\'s events wait in the dark, unread.',
  '🔍 Every word tonight is on paper. Making sense of it is a job for later.',
  '🪄 The recording sigil dims. What was spoken is captured and sealed.',
  '📖 Closing the Tome of Record. Nothing is lost; nothing is read yet.',
  '🧾 The guild scribe grumbles about everyone talking at once, and files it anyway.',
  '🕰️ The hourglass is turned on its side. Tonight keeps until it is called for.',
  '🐦 The familiar carries tonight\'s pages to the archive and roosts.',
  '🧠 Every word remembered, filed, and left for a quieter hour.',
  '⚗️ Tonight\'s chaos is bottled and shelved, waiting to be distilled.',
  '📚 Tonight\'s chapter is filed unopened in the grand campaign archive.',
  '🕸️ The threads of conversation are gathered up, tangles and all, for later.',
  '🪶 The raven returns to its perch. The reading can wait.',
  '🗝️ Tonight\'s secrets are locked away, safe until someone turns the key.',
  '🌒 The session ends and the ink dries. History can be read another day.',
  '🔮 The crystal ball goes dark, holding tonight\'s events until summoned.',
  '⏳ Recording stopped. Tonight is safely on the shelf.',
];

// {failCount}
export const LEAVE_NOTHING_USABLE = [
  '😶 Nothing but silence and static came through — {failCount} clip(s) failed to transcribe.',
  "🕸️ The scribe's notes came back blank. {failCount} recording(s) couldn't be read.",
  '📜 An empty scroll — transcription produced nothing usable ({failCount} failure(s)).',
  "🧙 'I... didn't catch any of that.' Transcription failed on {failCount} clip(s).",
  "🔇 The session was recorded, but the words didn't survive the journey ({failCount} failure(s)).",
  '🗝️ The vault opened onto an empty room — {failCount} clip(s) failed to transcribe.',
  '🐦 The familiar came back with nothing but scribbles ({failCount} failure(s)).',
  '📖 A blank page where a chapter should be — {failCount} clip(s) unreadable.',
  "🧾 The scroll came back smudged beyond reading ({failCount} failure(s)).",
  '🕯️ The candle burned out before the words could be caught ({failCount} failure(s)).',
  '🔮 The crystal ball only showed static — {failCount} clip(s) failed to transcribe.',
  '🌙 The night kept its secrets — {failCount} clip(s) came back unusable.',
  "⚗️ The distillation failed — nothing usable came through ({failCount} failure(s)).",
  '🕰️ Time swallowed those words whole — {failCount} clip(s) unreadable.',
  '🪶 The quill snapped mid-sentence — {failCount} clip(s) failed to transcribe.',
  "🧠 My memory of that session is a blank — {failCount} clip(s) unusable.",
  '🐉 Even the dragon shrugged — {failCount} clip(s) came through unreadable.',
  '🗿 The stones stayed silent — {failCount} clip(s) failed to transcribe.',
  '📯 The herald has nothing to announce — {failCount} clip(s) unusable.',
  '😶 Transcription produced nothing usable ({failCount} failure(s)).',
];

// {count}
export const LEAVE_SUMMARIZING_NOW = [
  '✅ {count} lines transcribed. The wizard is drafting your recap now.',
  '✅ {count} lines captured for posterity. Summoning the summary as we speak.',
  '✅ Transcribed {count} lines. A more learned mind is now distilling it into a proper recap.',
  '✅ {count} lines of glory (and rambling) recorded. Summarising now.',
  '✅ {count} lines saved to the annals. The recap-conjuring begins immediately.',
  '✅ {count} lines transcribed — handing this off to the Oracle for summarising.',
  '✅ Captured {count} lines of dialogue. Weaving them into a recap now.',
  "✅ {count} lines down. The scribe's apprentice is writing the summary.",
  '✅ Transcription complete — {count} lines. Recap incoming shortly.',
  '✅ {count} lines of session recorded. The summary spell is already being cast.',
  '✅ {count} lines transcribed. Turning chaos into a coherent recap now...',
  '✅ {count} lines saved. Your friendly neighbourhood AI is drafting the recap.',
  '✅ {count} lines of transcript ready. Summarising as we speak.',
  '✅ {count} lines archived. A recap is being conjured right now.',
  '✅ {count} lines transcribed successfully. Recap generation underway.',
  '✅ {count} lines of session lore captured. Summarising now, stand by.',
  '✅ Transcribed {count} lines — the summarising oracle is already at work.',
  '✅ {count} lines recorded for the ages. Summary coming right up.',
  '✅ {count} lines transcribed. The tale is being polished into a recap now.',
  '✅ Transcribed {count} lines. Summarising now...',
];

// {count}, {meetingId}, {label}
export const LEAVE_SUMMARY_QUEUED = [
  "✅ {count} lines transcribed, but {label} isn't answering right now. The recap is queued — or run `/summarise meeting_id:{meetingId}` once it's back.",
  '✅ {count} lines captured. Alas, {label} is unreachable. It\'ll retry automatically, or use `/summarise meeting_id:{meetingId}`.',
  "✅ {count} lines transcribed. {label} is elsewhere for now — the summary will wait patiently in the queue.",
  "✅ Transcription done ({count} lines) — but {label}'s tower is dark. It's queued for when it comes back.",
  "✅ {count} lines recorded. {label} appears to be powered down; I'll keep trying.",
  '✅ {count} lines saved. {label} isn\'t answering — queued for automatic retry, or `/summarise meeting_id:{meetingId}` manually.',
  "✅ {count} lines transcribed. No answer from {label} — it's queued until it returns.",
  '✅ {count} lines of dialogue captured. The summary awaits {label} waking up.',
  '✅ {count} lines down. {label} seems to be resting — the recap will follow once it stirs.',
  "✅ {count} lines transcribed successfully, but {label} isn't home. Queued for later.",
  "✅ {count} lines recorded. Summoning failed — {label} isn't reachable. It'll auto-retry.",
  "✅ {count} lines transcribed. {label}'s workshop is closed for now — queued.",
  '✅ {count} lines saved to the archive. Recap pending on {label}.',
  '✅ {count} lines of transcript ready, but no reply from {label}. Retrying automatically.',
  "✅ {count} lines transcribed. It seems {label} has wandered off — the summary awaits its return.",
  "✅ {count} lines captured. Recap queued; {label} isn't reachable right now.",
  '✅ {count} lines transcribed. {label} is currently offline — try `/summarise meeting_id:{meetingId}` later.',
  '✅ {count} lines recorded for the ages. Summary delayed — {label} sleeps.',
  '✅ {count} lines transcribed. Waiting on {label} to come back online for the recap.',
  "✅ Transcribed {count} lines. {label} isn't reachable right now — the summary is queued and will run automatically once it's back, or run `/summarise meeting_id:{meetingId}` to retry sooner.",
];

export const HISTORY_EMPTY = [
  '📭 The archive is bare — no sessions recorded yet.',
  "📜 An empty shelf — nothing's been recorded yet.",
  '🗝️ The vault has nothing in it yet. No sessions recorded.',
  '🧾 The ledger has yet to be opened. No sessions recorded yet.',
  "📖 This campaign's first chapter hasn't been written yet.",
  '🕯️ No candles have been lit for a session yet.',
  '🐦 The familiar has nothing to report — no sessions yet.',
  "🔮 The crystal ball shows nothing — no history to speak of yet.",
  '🧙 Not a single tale has been told yet. No sessions recorded.',
  '🌙 No nights have been chronicled yet.',
  "⚗️ Nothing's been distilled into history yet.",
  '🕸️ No threads have been woven into this archive yet.',
  '🧠 My memory is blank — no sessions recorded yet.',
  '🎙️ Nothing on the tape yet — no sessions recorded.',
  '🐉 The dragon\'s hoard of stories is empty so far.',
  '🗿 The stones have nothing carved into them yet.',
  '📯 No proclamations to make — no sessions yet.',
  "🧝 The chronicle begins with you — no sessions recorded yet.",
  '🕰️ Time has yet to record anything here.',
  '📭 No sessions recorded yet.',
];

// {label}
export const SUMMARIZE_UNREACHABLE = [
  "🔮 The Oracle's tower is dark — {label} still isn't reachable. It'll retry automatically too.",
  "🧙 Still no answer from {label}. It'll retry in the background.",
  '📡 Signal lost to {label} — the summarising wizard is still unreachable, but retries continue quietly.',
  "🕯️ Knocked on {label}'s door — no one home yet. Auto-retry is still running.",
  "🐦 The familiar returned empty-winged from {label} — still unreachable. It'll keep trying.",
  "⚗️ The distillation machine ({label}) is still cold. Background retries continue.",
  "🗝️ Still can't reach {label}'s chamber. Retrying automatically.",
  '{label} still isn\'t reachable. It\'ll retry automatically in the background too.',
  "🧾 No reply from {label} yet — the queue will keep knocking.",
  '🌙 {label} sleeps on. Background retries continue.',
  "🕰️ Still waiting on {label} to answer. Retrying automatically in the meantime.",
  '📖 That chapter awaits {label} — still unreachable, retrying quietly.',
  "🧠 My connection to {label} remains silent. Auto-retry continues.",
  '🐉 {label} is still asleep. Retries continue in the background.',
  '🗿 No echo back from {label} yet. Background retries continue.',
  '📯 No herald could reach {label} — still unreachable, retrying automatically.',
  "🧝 The messenger sent to {label} hasn't returned. Retrying automatically.",
  '⛩️ The shrine of {label} remains dark. Auto-retry continues quietly.',
  "🪶 Still no word back from {label}. It'll retry automatically too.",
  "{label} still isn't reachable. It'll retry automatically in the background too.",
];

// {meetingId}
export const SUMMARIZE_QUEUED = [
  '🔮 Queued meeting #{meetingId} for an immediate retry — check back shortly.',
  '🧙 Meeting #{meetingId} has been shoved to the front of the queue. Check back shortly.',
  '📜 Meeting #{meetingId} is up next for summarising — check back shortly.',
  "⚗️ Re-distilling meeting #{meetingId} right now — check back shortly.",
  '🕯️ Meeting #{meetingId} moves to the top of the pile. Check back shortly.',
  '🐦 The familiar has been sent to fetch a summary for meeting #{meetingId}. Check back shortly.',
  '🗝️ Meeting #{meetingId} queued for immediate retry — check back shortly.',
  '🧾 Meeting #{meetingId} is next on the scribe\'s desk. Check back shortly.',
  '📖 Reopening meeting #{meetingId} for a fresh summary attempt. Check back shortly.',
  '🌙 Meeting #{meetingId} gets another chance tonight — check back shortly.',
  '🕰️ Meeting #{meetingId} bumped up the queue. Check back shortly.',
  '🧠 Recalling meeting #{meetingId} once more — check back shortly.',
  '🎙️ Re-queued meeting #{meetingId} for summarising — check back shortly.',
  '🐉 Meeting #{meetingId} goes back into the furnace for another attempt.',
  '🗿 Meeting #{meetingId} carved back into the queue. Check back shortly.',
  '📯 Meeting #{meetingId} announced for another summarising attempt.',
  '🧝 Meeting #{meetingId} handed back to the chronicler. Check back shortly.',
  '⛩️ Meeting #{meetingId} placed back on the altar for summarising.',
  '🪶 Meeting #{meetingId} queued once more — check back shortly.',
  'Queued meeting #{meetingId} for immediate retry — check back shortly.',
];

// {meetingId}, {channel}, {date}
export const EXPORT_INTRO = [
  "📜 Here's the full transcript for meeting #{meetingId} ({channel}, {date}).",
  "🗝️ Unsealing the archive for meeting #{meetingId} ({channel}, {date}).",
  '📖 Pulling meeting #{meetingId} ({channel}, {date}) off the shelf for you.',
  "🧾 The scroll for meeting #{meetingId} ({channel}, {date}), delivered.",
  "🕯️ Dusting off the record of meeting #{meetingId} ({channel}, {date}).",
  '🐦 The familiar fetches the transcript for meeting #{meetingId} ({channel}, {date}).',
  "🔮 Replaying meeting #{meetingId} ({channel}, {date}) from the archive.",
  '🧙 Here is what was said in meeting #{meetingId} ({channel}, {date}).',
  "🌙 The record of that night — meeting #{meetingId} ({channel}, {date}).",
  '⚗️ The distilled transcript of meeting #{meetingId} ({channel}, {date}).',
  '🕰️ Turning back the clock to meeting #{meetingId} ({channel}, {date}).',
  '🧠 Everything recalled from meeting #{meetingId} ({channel}, {date}).',
  '🎙️ The full tape of meeting #{meetingId} ({channel}, {date}).',
  '🐉 The hoard yields the transcript for meeting #{meetingId} ({channel}, {date}).',
  '🗿 Carved in full: meeting #{meetingId} ({channel}, {date}).',
  '📯 Announcing the transcript for meeting #{meetingId} ({channel}, {date}).',
  '🧝 The chronicle of meeting #{meetingId} ({channel}, {date}), retrieved.',
  '⛩️ Retrieved from the shrine: meeting #{meetingId} ({channel}, {date}).',
  '🪶 The full quill-work of meeting #{meetingId} ({channel}, {date}).',
  "Transcript for meeting #{meetingId} ({channel}, {date}).",
];

// {name}
export const SETCHARACTER_CONFIRM = [
  "🧙 Noted — you'll appear as **{name}** in every transcript and recap from now on.",
  "📜 Your true name has been inscribed: **{name}**. That's how you'll show up from now on.",
  "🗝️ The archive now knows you as **{name}**.",
  "🧾 Recorded in the ledger: you are **{name}** henceforth.",
  "🕯️ By candlelight, your name is set: **{name}**.",
  "🐦 The familiar will now call you **{name}** in every record.",
  "🔮 The crystal ball now sees you as **{name}**.",
  "🧝 From this session on, you're known in the chronicles as **{name}**.",
  "🌙 Under this name you shall be remembered: **{name}**.",
  "⚗️ Distilled down to one true name: **{name}**.",
  "🕰️ History will record you as **{name}** from here on.",
  "🧠 Committed to memory: you are **{name}**.",
  "🎙️ On record: you're **{name}** from now on.",
  "🐉 Even the dragon will note you as **{name}** going forward.",
  "🗿 Carved into the stone: **{name}**.",
  "📯 Let it be announced: you are **{name}**.",
  "⛩️ The shrine accepts your name: **{name}**.",
  "🪶 Inked in for good: **{name}**.",
  "🧙‍♂️ Got it — you'll show up as **{name}** in transcripts and notes from now on.",
  "Got it — you'll show up as **{name}** in transcripts and notes from now on.",
];

// {reachable}, {label}
export const STATUS_IDLE = [
  '😴 Nothing queued for summarising right now. {label} is currently {reachable}.',
  '🧙 All caught up — nothing waiting to be summarised. {label} is currently {reachable}.',
  '📜 The desk is clear — no sessions queued. {label} is currently {reachable}.',
  '🕯️ Nothing left to distill right now. {label} is currently {reachable}.',
  '🗝️ The queue is empty. {label} is currently {reachable}.',
  '🐦 No errands for the familiar right now. {label} is currently {reachable}.',
  '🔮 The crystal ball shows an empty queue. {label} is currently {reachable}.',
  '🧾 Nothing pending in the ledger. {label} is currently {reachable}.',
  '🌙 A quiet night — nothing queued. {label} is currently {reachable}.',
  "⚗️ Nothing's brewing right now. {label} is currently {reachable}.",
  '🕰️ No time being spent waiting right now. {label} is currently {reachable}.',
  '🧠 Nothing on my mind right now. {label} is currently {reachable}.',
  '🎙️ Nothing queued. {label} is currently {reachable}.',
  "🐉 The dragon's ledger is empty for now. {label} is currently {reachable}.",
  '🗿 No inscriptions pending. {label} is currently {reachable}.',
  '📯 Nothing to announce right now. {label} is currently {reachable}.',
  '🧝 All quiet on the chronicle front. {label} is currently {reachable}.',
  '⛩️ The altar is clear. {label} is currently {reachable}.',
  '🪶 The quill rests idle. {label} is currently {reachable}.',
  'No sessions currently queued for summarisation. {label} is currently {reachable}.',
];

// {reachable}, {label}
export const STATUS_QUEUED_HEADER = [
  '🔮 {label} is currently {reachable}.\n\n**Queued:**',
  "🧙 {label} is currently {reachable}. Here's what's waiting:\n\n**Queued:**",
  '📜 {label} is currently {reachable}. The queue so far:\n\n**Queued:**',
  '🕯️ {label} status: {reachable}.\n\n**Queued:**',
  '🗝️ {label} is currently {reachable}. Waiting in the vault:\n\n**Queued:**',
  '🐦 {label} is currently {reachable}. Errands pending:\n\n**Queued:**',
  '🧾 {label} is currently {reachable}. On the ledger:\n\n**Queued:**',
  '🌙 {label} is currently {reachable}. Still to be told:\n\n**Queued:**',
  '⚗️ {label} is currently {reachable}. Still brewing:\n\n**Queued:**',
  '🕰️ {label} is currently {reachable}. Waiting on time:\n\n**Queued:**',
  '🧠 {label} is currently {reachable}. On my mind:\n\n**Queued:**',
  '🎙️ {label} is currently {reachable}. On the tape, unsummarised:\n\n**Queued:**',
  "🐉 {label} is currently {reachable}. In the dragon's ledger:\n\n**Queued:**",
  '🗿 {label} is currently {reachable}. Awaiting inscription:\n\n**Queued:**',
  '📯 {label} is currently {reachable}. To be announced:\n\n**Queued:**',
  '🧝 {label} is currently {reachable}. Awaiting the chronicler:\n\n**Queued:**',
  '⛩️ {label} is currently {reachable}. Upon the altar:\n\n**Queued:**',
  '🪶 {label} is currently {reachable}. Awaiting ink:\n\n**Queued:**',
  '🔮 {label} is currently {reachable}.\n\n**Queued:**',
  '{label} is currently {reachable}.\n\n**Queued:**',
];

export const RECAP_NONE = [
  '📭 No completed sessions yet — nothing to recap.',
  "📜 The chronicle hasn't its first finished chapter yet.",
  '🗝️ The vault holds no finished tales yet.',
  '🧾 No completed sessions in the ledger yet.',
  "🕯️ No candle has burned through a full recap yet.",
  '🐦 The familiar has nothing finished to recite yet.',
  '🔮 The crystal ball shows no completed sessions yet.',
  '🧙 No recap exists yet — the tale is still being written.',
  '🌙 No night has reached its recap yet.',
  "⚗️ Nothing's been fully distilled into a recap yet.",
  '🕰️ History has no finished chapter to recall yet.',
  '🧠 My memory holds no completed recaps yet.',
  '🎙️ Nothing finished on the tape yet.',
  "🐉 The dragon's hoard has no finished tales yet.",
  '🗿 No stone bears a finished recap yet.',
  '📯 Nothing to proclaim yet — no completed sessions.',
  '🧝 The chronicler awaits a finished tale.',
  '⛩️ The shrine holds no completed recap yet.',
  '🪶 No ink has dried on a finished recap yet.',
  'No completed sessions yet.',
];

// {channel}, {date}
export const RECAP_HEADER = [
  '📜 **Recap — {channel} ({date})**',
  '🧙 **The Tale So Far — {channel} ({date})**',
  '🗝️ **From the Archive — {channel} ({date})**',
  '🕯️ **By Candlelight — {channel} ({date})**',
  '🐦 **As the Familiar Recalls — {channel} ({date})**',
  '🔮 **The Crystal Ball Remembers — {channel} ({date})**',
  '🌙 **Last We Left Off — {channel} ({date})**',
  '⚗️ **Distilled Memory — {channel} ({date})**',
  '🕰️ **A Look Back — {channel} ({date})**',
  '🧠 **What I Remember — {channel} ({date})**',
  '🎙️ **Previously, on {channel} ({date})**',
  '🐉 **From the Hoard — {channel} ({date})**',
  '🗿 **Carved in Stone — {channel} ({date})**',
  '📯 **Hear Ye — {channel} ({date})**',
  '🧝 **The Chronicler Speaks — {channel} ({date})**',
  '⛩️ **From the Shrine — {channel} ({date})**',
  '🪶 **Ink Still Fresh — {channel} ({date})**',
  '📖 **Last Chapter — {channel} ({date})**',
  '🧾 **On the Ledger — {channel} ({date})**',
  '📜 **Recap — {channel} ({date})**',
];

// {channel}, {date}
export const POST_SESSION_HEADER = [
  '# 🐉 Session Recap — {channel} ({date})',
  '# 🧙 The Wizard\'s Notes — {channel} ({date})',
  '# 📜 Chronicle Entry — {channel} ({date})',
  '# 🕯️ By Candlelight — {channel} ({date})',
  '# 🗝️ From the Archive — {channel} ({date})',
  '# 🐦 The Familiar Reports — {channel} ({date})',
  '# 🔮 The Crystal Ball Recalls — {channel} ({date})',
  '# 🌙 Last Night\'s Tale — {channel} ({date})',
  '# ⚗️ Distilled Memories — {channel} ({date})',
  '# 🕰️ A Look Back — {channel} ({date})',
  '# 🧠 What Was Remembered — {channel} ({date})',
  '# 🎙️ Previously... — {channel} ({date})',
  '# 🗿 Carved in Stone — {channel} ({date})',
  '# 📯 Hear Ye, Hear Ye — {channel} ({date})',
  '# 🧝 The Chronicler\'s Account — {channel} ({date})',
  '# ⛩️ From the Shrine of Record — {channel} ({date})',
  '# 🪶 Fresh Ink — {channel} ({date})',
  '# 📖 Another Chapter Closes — {channel} ({date})',
  '# 🧾 The Guild Ledger — {channel} ({date})',
  '# 🐉 Session Recap — {channel} ({date})',
];

export const POST_SESSION_ATTACHMENT_CAPTION = [
  '📎 Full session markdown (transcript + notes) — drop into Obsidian:',
  '📎 The complete chronicle, ready for your Obsidian vault:',
  '📎 Everything that happened, in full — for Obsidian:',
  '📎 The unabridged record (transcript + notes), Obsidian-ready:',
  '📎 A copy for the archive — drop this into Obsidian:',
  '📎 The full scroll, transcript and all, for Obsidian:',
  '📎 Complete notes attached — Obsidian-ready as always:',
  '📎 The whole session, transcribed and summarised, for your vault:',
  '📎 Here\'s the full write-up (transcript + notes) for Obsidian:',
  '📎 Filed and ready — full session markdown for Obsidian:',
  '📎 The complete record, transcript included, Obsidian-ready:',
  '📎 Nothing left out — full markdown for your Obsidian vault:',
  '📎 The definitive account (transcript + notes) — Obsidian-ready:',
  '📎 Everything said and summarised, packaged for Obsidian:',
  '📎 The full session file, ready to drop into your vault:',
  '📎 Complete transcript + notes, Obsidian-formatted:',
  '📎 The whole record, start to finish, for Obsidian:',
  '📎 A full accounting of tonight, Obsidian-ready:',
  '📎 The archive copy — transcript and notes, for Obsidian:',
  '📎 Full session markdown (transcript + notes) — drop into Obsidian:',
];

export const FUNNY_NONE = [
  "🤷 Nothing funny on record yet — either you've all been very sensible, or nobody's cast Fireball indoors yet.",
  "😐 No memorable chaos recorded so far. Give it time.",
  '🧙 The scribe has yet to write down anything worth laughing about. A quiet campaign, so far.',
  "📜 The archive of foolishness is empty. Surely that won't last.",
  "🎭 No blooper reel yet — this campaign is being suspiciously well-behaved.",
  '🧾 Nothing filed under "chaos" yet.',
  "🕯️ Not a single recorded disaster yet. Impressive, honestly.",
  "🐦 The familiar hasn't overheard anything worth repeating yet.",
  '🔮 The crystal ball shows a distinct lack of tomfoolery so far.',
  "🌙 No embarrassing moments on the books yet.",
  "⚗️ Nothing chaotic enough to bottle yet.",
  "🕰️ History hasn't recorded a single blunder yet.",
  "🧠 I've got nothing funny filed away yet — ask again after a few more sessions.",
  "🎙️ Nothing on the blooper tape yet.",
  "🐉 Even the dragon hasn't seen anything worth laughing at yet.",
  '🗿 No moment has been carved into the "hall of shame" yet.',
  "📯 Nothing embarrassing enough to announce yet.",
  "🧝 The chronicler hasn't caught anyone doing anything silly yet.",
  "⛩️ The shrine of chaos stands empty, for now.",
  "🪶 Not a single funny quill-mark yet — give the party time.",
];

// {channel}, {date}, {moment}
export const FUNNY_HEADER = [
  '😂 Remember when, back in **{channel}** ({date})... {moment}',
  '🎭 A moment worth remembering, from **{channel}** ({date}):\n\n{moment}',
  '🧙 Pulled from the archive — **{channel}** ({date}):\n\n{moment}',
  '📜 Straight from the record books, **{channel}** ({date}):\n\n{moment}',
  '🐦 The familiar recalls, from **{channel}** ({date}):\n\n{moment}',
  '🔮 The crystal ball shows a memory from **{channel}** ({date}):\n\n{moment}',
  '🌙 A blast from the past — **{channel}** ({date}):\n\n{moment}',
  '⚗️ A distilled memory from **{channel}** ({date}):\n\n{moment}',
  '🕰️ Turning back the clock to **{channel}** ({date})...\n\n{moment}',
  '🧠 I remember this one — **{channel}** ({date}):\n\n{moment}',
  '🎙️ Pulled at random from the tape — **{channel}** ({date}):\n\n{moment}',
  '🐉 From the hoard of chaos, **{channel}** ({date}):\n\n{moment}',
  '🗿 Carved into the hall of shame — **{channel}** ({date}):\n\n{moment}',
  '📯 Hear ye — a moment from **{channel}** ({date}):\n\n{moment}',
  '🧝 The chronicler grins and recalls, from **{channel}** ({date}):\n\n{moment}',
  '⛩️ From the shrine of chaos, **{channel}** ({date}):\n\n{moment}',
  '🪶 A moment worth re-inking — **{channel}** ({date}):\n\n{moment}',
  '📖 Flipping back to **{channel}** ({date})...\n\n{moment}',
  '🧾 On record, from **{channel}** ({date}):\n\n{moment}',
  '😂 A random moment worth remembering — **{channel}** ({date}):\n\n{moment}',
];

// {error}
export const JOIN_FAILED = [
  "🧙 The scribe tried to slip into the room but the door wouldn't open: {error}",
  '📜 The quill snapped before a single word was written: {error}',
  "🕯️ The candle refused to light — couldn't establish the connection: {error}",
  '🔮 The crystal ball stayed dark — voice connection failed: {error}',
  "🗝️ The lock wouldn't turn — couldn't join the voice channel: {error}",
  '🐦 The familiar flew into a window — connection failed: {error}',
  "🧾 The scroll never unrolled — joining failed: {error}",
  '📖 That chapter refused to open — voice connection failed: {error}',
  "🌙 Something in the ether blocked the way — couldn't connect: {error}",
  "⚗️ The ritual fizzled before it began — connection failed: {error}",
  "🕸️ The threads snapped before they could weave — couldn't connect: {error}",
  "🧠 Lost the signal before it even started — connection failed: {error}",
  '🎙️ Nothing came through — voice connection failed: {error}',
  "🐉 Even the dragon couldn't force the door — connection failed: {error}",
  '🗿 The stones stayed silent — connection failed: {error}',
  "📯 The herald never made it through — connection failed: {error}",
  "🧝 The chronicler got turned away at the door — connection failed: {error}",
  '⛩️ The shrine remained sealed — connection failed: {error}',
  '🪶 The quill never touched parchment — connection failed: {error}',
  "😬 Couldn't actually start recording — the voice connection failed: {error}. Nothing was recorded — try `/join` again.",
];

// {query}
export const SEARCH_NONE = [
  '🔍 Nothing in the archive matches "{query}".',
  '📜 The scribe flipped through every scroll and found no mention of "{query}".',
  '🕯️ No record of "{query}" anywhere in the chronicle.',
  '🗝️ The vault holds nothing matching "{query}".',
  '🐦 The familiar searched the whole archive and came back with nothing for "{query}".',
  '🔮 The crystal ball shows no memory of "{query}".',
  '🧙 "{query}"? I have no recollection of that being said.',
  '🧾 Not a single line in the ledger mentions "{query}".',
  '📖 No chapter contains "{query}".',
  '🌙 Nothing on record for "{query}".',
  '⚗️ Nothing in the archive distills down to "{query}".',
  '🕸️ No thread in the tapestry matches "{query}".',
  '🧠 I have no memory of "{query}" being spoken.',
  '🎙️ Nothing on any tape matches "{query}".',
  '🐉 The dragon\'s hoard contains no "{query}".',
  '🗿 No stone bears the words "{query}".',
  '📯 Nothing to announce — no matches for "{query}".',
  '🧝 The chronicler cannot recall "{query}" at all.',
  '⛩️ The shrine holds no record of "{query}".',
  '🪶 No ink was ever spilled on "{query}".',
];

// {query}, {count}
export const SEARCH_HEADER = [
  '🔍 Found {count} mention(s) of "{query}" in the archive:',
  '📜 The scribe dug up {count} mention(s) of "{query}":',
  '🗝️ Unsealed {count} record(s) mentioning "{query}":',
  '🕯️ By candlelight, {count} mention(s) of "{query}":',
  '🐦 The familiar retrieved {count} mention(s) of "{query}":',
  '🔮 The crystal ball replays {count} moment(s) mentioning "{query}":',
  '🧙 I remember "{query}" — {count} time(s), in fact:',
  '🧾 The ledger records {count} mention(s) of "{query}":',
  '📖 {count} passage(s) mention "{query}":',
  '🌙 {count} moment(s) in the chronicle mention "{query}":',
  '⚗️ Distilled {count} mention(s) of "{query}" from the archive:',
  '🕰️ Turning back the clock — {count} mention(s) of "{query}":',
  '🧠 {count} memory(s) surfaced for "{query}":',
  '🎙️ {count} moment(s) on tape mention "{query}":',
  '🐉 The hoard yields {count} mention(s) of "{query}":',
  '🗿 {count} inscription(s) mention "{query}":',
  '📯 Announcing {count} mention(s) of "{query}":',
  '🧝 The chronicler recalls {count} mention(s) of "{query}":',
  '⛩️ The shrine surrenders {count} mention(s) of "{query}":',
  '🪶 {count} line(s) of ink mention "{query}":',
];

// {meetingId}, {channel}, {date}, {count}
export const APPROVAL_REQUEST = [
  '📜 The transcript for **{channel}** ({date}) is written — {count} lines, session #{meetingId}. The oracle awaits your word before it starts thinking.',
  '🧙 Session #{meetingId} (**{channel}**, {date}) is transcribed: {count} lines. Say when, and I\'ll wake the summarising wizard.',
  '🕯️ {count} lines copied out from **{channel}** ({date}). Session #{meetingId} is ready whenever your machine is.',
  '🐦 The familiar has finished its scribbling for **{channel}** ({date}) — {count} lines. Shall I send it to the oracle? (session #{meetingId})',
  '⏳ Session #{meetingId} (**{channel}**, {date}) is transcribed and waiting — {count} lines. Nothing will touch your GPU until you say so.',
  '🗝️ The vault holds {count} fresh lines from **{channel}** ({date}). Session #{meetingId} awaits your approval.',
  '📖 Session #{meetingId} — **{channel}** ({date}), {count} lines — is ready to be turned into a recap. Your call.',
  '🔮 The crystal ball has recorded {count} lines from **{channel}** ({date}). Summoning the summary is up to you (session #{meetingId}).',
  '🧾 The ledger for **{channel}** ({date}) is complete: {count} lines. Session #{meetingId} is parked until you approve.',
  '🌙 {count} lines from **{channel}** ({date}) are safely written down. Session #{meetingId} waits on your word.',
  '⚗️ The raw ingredients are ready — {count} lines from **{channel}** ({date}). Say the word and I\'ll start distilling session #{meetingId}.',
  '🕰️ Session #{meetingId} (**{channel}**, {date}) transcribed: {count} lines. Held back so it doesn\'t steal your GPU mid-fight.',
  '🧠 I\'ve memorised {count} lines from **{channel}** ({date}). Session #{meetingId} is ready when you are.',
  '🎙️ The tape is cut — {count} lines from **{channel}** ({date}). Approve session #{meetingId} when your machine is free.',
  '🐉 The hoard has grown by {count} lines (**{channel}**, {date}). Session #{meetingId} awaits your blessing.',
  '🗿 {count} lines carved from **{channel}** ({date}). Session #{meetingId} is parked, awaiting approval.',
  '📯 Hear ye: session #{meetingId} (**{channel}**, {date}) is transcribed — {count} lines — and awaiting your go-ahead.',
  '🧝 The chronicler has finished **{channel}** ({date}) — {count} lines. Session #{meetingId} needs your nod before summarising.',
  '⛩️ {count} lines offered at the shrine from **{channel}** ({date}). Session #{meetingId} rests until you approve.',
  '🪶 The ink is dry on {count} lines from **{channel}** ({date}). Session #{meetingId} is ready for the summariser — your call.',
];

// {count}, {meetingId}
export const LEAVE_AWAITING_APPROVAL = [
  '✅ {count} lines transcribed. Parked awaiting your approval — I won\'t touch your GPU until you say so (session #{meetingId}).',
  '✅ {count} lines captured. The summary is held back until you approve it (session #{meetingId}).',
  '✅ Transcription done — {count} lines. Waiting on your word before summoning the oracle (session #{meetingId}).',
  '✅ {count} lines saved. The summarising wizard stays asleep until you wake him (session #{meetingId}).',
  '✅ {count} lines written down. Nothing goes to the summariser until you approve session #{meetingId}.',
  '✅ {count} lines archived. Summary parked — approve session #{meetingId} whenever your machine is free.',
  '✅ {count} lines transcribed and waiting. Your GPU stays untouched until you approve session #{meetingId}.',
  '✅ {count} lines down. The recap is on hold pending your approval (session #{meetingId}).',
  '✅ {count} lines recorded. I\'ll wait for your go-ahead before summarising session #{meetingId}.',
  '✅ {count} lines captured, summary deliberately not started. Approve session #{meetingId} when ready.',
  '✅ {count} lines transcribed. Holding the summary back so it doesn\'t cook your framerate (session #{meetingId}).',
  '✅ {count} lines safe on disk. Session #{meetingId} awaits your approval to summarise.',
  '✅ {count} lines noted. The oracle sleeps until summoned — approve session #{meetingId}.',
  '✅ {count} lines transcribed successfully. Summary parked for session #{meetingId}.',
  '✅ {count} lines of session captured. Awaiting your approval before the AI does anything (session #{meetingId}).',
  '✅ {count} lines stored. The summarising step is yours to trigger (session #{meetingId}).',
  '✅ {count} lines transcribed. Nothing further happens until you approve session #{meetingId}.',
  '✅ {count} lines in the archive. Approve session #{meetingId} to generate the recap.',
  '✅ {count} lines ready. The recap waits on your command (session #{meetingId}).',
  '✅ {count} lines transcribed — summary parked pending approval (session #{meetingId}).',
];

// {meetingId}
export const APPROVED_CONFIRM = [
  '🔮 Approved — session #{meetingId} is off to the oracle now.',
  '🧙 The wizard stirs. Summarising session #{meetingId} now.',
  '⚗️ Distillation begins on session #{meetingId}.',
  '🕯️ Candle lit — session #{meetingId} is being summarised.',
  '🐦 The familiar flies to the oracle with session #{meetingId}.',
  '📜 Session #{meetingId} approved and queued for summarising.',
  '🗝️ Unlocked — session #{meetingId} is being summarised now.',
  '🧾 Session #{meetingId} released to the summariser.',
  '📖 Writing the recap for session #{meetingId} now.',
  '🌙 Session #{meetingId} approved — the recap is being conjured.',
  '🕰️ Session #{meetingId} is on the clock now.',
  '🧠 Thinking hard about session #{meetingId}...',
  '🎙️ Session #{meetingId} sent off for summarising.',
  '🐉 The dragon wakes for session #{meetingId}.',
  '🗿 Session #{meetingId} approved — carving the recap now.',
  '📯 Session #{meetingId} announced to the oracle.',
  '🧝 The chronicler takes up session #{meetingId}.',
  '⛩️ Session #{meetingId} accepted at the shrine.',
  '🪶 Quill to parchment for session #{meetingId}.',
  '✅ Approved — summarising session #{meetingId} now.',
];

// {meetingId}
export const PARKED_CONFIRM = [
  '💤 Left parked. Session #{meetingId} will wait as long as you need.',
  '🕯️ Understood — session #{meetingId} stays on the shelf.',
  '📜 Session #{meetingId} remains rolled up and waiting.',
  '🧙 The wizard goes back to sleep. Session #{meetingId} is still parked.',
  '🌙 Session #{meetingId} rests until you say otherwise.',
  '🗝️ Still locked away — session #{meetingId} awaits a later moment.',
  '🐦 The familiar settles back down. Session #{meetingId} is parked.',
  '🧾 Session #{meetingId} stays on the ledger, unprocessed.',
  '⏳ No rush — session #{meetingId} will keep.',
  '📖 Session #{meetingId} stays closed for now.',
  '⚗️ Ingredients kept fresh — session #{meetingId} is still waiting.',
  '🕰️ Session #{meetingId} is in no hurry.',
  '🧠 Filed away — session #{meetingId} remains pending.',
  '🎙️ Session #{meetingId} stays on the shelf.',
  '🐉 The dragon dozes on. Session #{meetingId} is parked.',
  '🗿 Session #{meetingId} remains uncarved for now.',
  '🧝 The chronicler waits. Session #{meetingId} is parked.',
  '⛩️ Session #{meetingId} rests at the shrine.',
  '🪶 Quill down — session #{meetingId} still waiting.',
  '💤 Fine by me — session #{meetingId} stays parked until you approve it.',
];

export const QUEUE_PAUSED = [
  '⏸️ Summarising paused. Safe to restart your summariser — nothing will try to reach it.',
  '🛑 The oracle will not be disturbed. Summarising is paused.',
  '🕯️ Candles snuffed — no summaries will run until you resume.',
  '🧙 The wizard has been told to stand down. Summarising paused.',
  '💤 Summarising paused. Restart or reconfigure freely; the queue keeps everything safe.',
  '🗝️ Queue locked. Nothing will be sent to the summariser until you resume.',
  '📜 The quill rests. Summarising is paused.',
  '⚗️ Distillation halted. Nothing will run until you resume.',
  '🌙 All quiet — summarising paused.',
  '🐦 The familiar has been recalled. No summaries will run.',
  '🕰️ Time stopped for the summariser. Paused.',
  '🧠 I\'ll stop thinking for now. Summarising paused.',
  '🎙️ Summarising paused — nothing queued will run.',
  '🐉 The dragon sleeps. Summarising paused.',
  '🗿 The stones are still. Summarising paused.',
  '📯 Let it be known: summarising is paused.',
  '🧝 The chronicler downs tools. Summarising paused.',
  '⛩️ The shrine is closed. Summarising paused.',
  '🪶 Ink stoppered — summarising paused.',
  '⏸️ Paused. Nothing will be summarised until you run `/resume`.',
];

export const QUEUE_RESUMED = [
  '▶️ Summarising resumed — the queue is moving again.',
  '🔮 The oracle is back on duty. Summarising resumed.',
  '🕯️ Candles relit. Summarising resumed.',
  '🧙 The wizard returns to his desk. Summarising resumed.',
  '📜 The quill moves again — summarising resumed.',
  '⚗️ Distillation restarted. Summarising resumed.',
  '🌙 Back to work — summarising resumed.',
  '🐦 The familiar takes flight again. Summarising resumed.',
  '🗝️ Queue unlocked. Summarising resumed.',
  '🕰️ Time flows again for the summariser. Resumed.',
  '🧠 Thinking resumed.',
  '🎙️ Summarising resumed — anything queued will run shortly.',
  '🐉 The dragon wakes. Summarising resumed.',
  '🗿 The stones stir. Summarising resumed.',
  '📯 Summarising resumed, by proclamation.',
  '🧝 The chronicler picks up the quill. Summarising resumed.',
  '⛩️ The shrine reopens. Summarising resumed.',
  '🪶 Ink flowing again — summarising resumed.',
  '📖 The tome reopens. Summarising resumed.',
  '▶️ Resumed. Queued sessions will be summarised shortly.',
];

export const PENDING_EMPTY = [
  '📭 The pipeline is completely clear — nothing recording, transcribing, or waiting.',
  '🧙 Nothing in flight. The workshop is empty.',
  '📜 No scrolls in progress. The pipeline is clear.',
  '🕯️ Nothing burning — the pipeline is empty.',
  '🗝️ The vault is quiet. Nothing pending.',
  '🐦 The familiar has nothing to report. Pipeline clear.',
  '🔮 The crystal ball shows an empty pipeline.',
  '🧾 Nothing on the ledger. All clear.',
  '📖 No chapters in progress.',
  '🌙 A quiet night — nothing in the pipeline.',
  '⚗️ Nothing brewing at all.',
  '🕸️ No threads in progress.',
  '🧠 Nothing on my mind — pipeline clear.',
  '🎙️ Nothing rolling, nothing queued.',
  '🐉 The dragon\'s desk is clear.',
  '🗿 Nothing being carved. Pipeline empty.',
  '📯 Nothing to announce — pipeline clear.',
  '🧝 The chronicler is idle. Nothing pending.',
  '⛩️ The shrine is empty. Nothing pending.',
  '🪶 Quill idle — nothing in the pipeline.',
];

// {wrong}, {right}, {count}
export const CORRECT_APPLIED = [
  '✏️ Noted — "{wrong}" is really **{right}**. Fixed {count} line(s), and I\'ll correct it automatically from now on.',
  '🧙 Ah, **{right}** — not "{wrong}". Corrected {count} line(s) and remembered it for future sessions.',
  '📜 The scribe amends the record: "{wrong}" → **{right}**. {count} line(s) rewritten, and it\'ll stick.',
  '🪶 Struck through "{wrong}", written **{right}**. {count} line(s) fixed; future sessions will match.',
  '🗝️ "{wrong}" now reads **{right}** throughout the archive — {count} line(s) — and stays that way.',
  '🧾 Ledger amended: "{wrong}" is **{right}**. {count} line(s) updated, correction saved.',
  '📖 Every "{wrong}" is now **{right}** — {count} line(s) — and I\'ll keep it that way.',
  '🐦 The familiar went back through the archive: "{wrong}" → **{right}**, {count} line(s) fixed.',
  '🔮 The record clears: "{wrong}" was always **{right}**. {count} line(s) corrected.',
  '🕯️ By candlelight the error is mended — "{wrong}" → **{right}**, {count} line(s).',
  '⚗️ Refined "{wrong}" into **{right}** across {count} line(s). It\'ll hold for future sessions.',
  '🕰️ History rewritten (for the better): "{wrong}" → **{right}**, {count} line(s).',
  '🧠 Re-remembered: **{right}**, not "{wrong}". {count} line(s) corrected and saved.',
  '🎙️ The tape is patched — "{wrong}" → **{right}** on {count} line(s).',
  '🐉 Even the dragon agrees it\'s **{right}**, not "{wrong}". {count} line(s) fixed.',
  '🗿 Re-carved: "{wrong}" → **{right}**, across {count} line(s).',
  '📯 Let the record show **{right}**, not "{wrong}" — {count} line(s) amended.',
  '🧝 The chronicler corrects themselves: **{right}**. {count} line(s) updated.',
  '⛩️ The name **{right}** replaces "{wrong}" on {count} line(s), now and hereafter.',
  '✏️ Corrected "{wrong}" → **{right}** on {count} line(s), and saved so future transcripts match.',
];

// {wrong}
export const UNCORRECT_APPLIED = [
  '🧙 Undone — "{wrong}" will go back to transcribing as whisper actually hears it.',
  '📜 Struck from the ledger — the correction for "{wrong}" is removed.',
  '🗝️ Unlocked "{wrong}" from its old fix. Future transcripts are unaffected by it now.',
  '🪶 Erased — "{wrong}" is no longer auto-corrected.',
  '🧾 Removed "{wrong}" from the saved corrections.',
  '⚗️ Reversed the distillation — "{wrong}" corrects to nothing now.',
  '🕯️ The old fix for "{wrong}" has been snuffed out.',
  '🌙 "{wrong}" is free again — no correction applies to it anymore.',
  "🐦 The familiar forgets that one — \"{wrong}\" is no longer corrected.",
  '✏️ Correction for "{wrong}" removed. Past transcripts are unchanged; only future ones stop applying it.',
];

// {name}
export const WHOAMI_SET = [
  '🧙 You appear in every transcript and recap as **{name}**.',
  "📜 The archive knows you as **{name}**.",
  "🗝️ Your recorded name is **{name}**.",
  "🧾 On the ledger, you're **{name}**.",
  "🕯️ By candlelight you're known as **{name}**.",
  "🐦 The familiar calls you **{name}**.",
  "🔮 The crystal ball sees you as **{name}**.",
  "🧝 You're chronicled as **{name}**.",
  "🌙 Under this name you're remembered: **{name}**.",
  "🎙️ On record, you're **{name}**.",
];

// {discordName}
export const WHOAMI_UNSET = [
  "🧙 No character name set — you'll show up as your Discord name, **{discordName}**. Set one with `/setcharacter`.",
  "📜 Nothing inscribed yet — transcripts use **{discordName}** until you `/setcharacter`.",
  "🗝️ No true name on file. Currently recorded as **{discordName}** — `/setcharacter` to change that.",
  "🧾 The ledger has you as **{discordName}** (your Discord name). Use `/setcharacter` to set something else.",
  "🕯️ Unset — you appear as **{discordName}** for now. `/setcharacter` to give yourself a proper name.",
  "🐦 The familiar only knows your Discord name, **{discordName}**. `/setcharacter` fixes that.",
  "🧝 No character name yet — **{discordName}** it is, until you `/setcharacter`.",
];

// {sessions}, {hours}, {lines}
export const STATS_HEADER = [
  '📊 **{sessions}** session(s), **{hours}h** recorded, **{lines}** lines transcribed.',
  '🧾 The ledger totals **{sessions}** session(s) — **{hours}h**, **{lines}** lines.',
  '📜 Across **{sessions}** session(s): **{hours}h** of tape, **{lines}** lines transcribed.',
  '🗝️ The vault holds **{sessions}** session(s) — **{hours}h**, **{lines}** lines.',
  '🕰️ **{hours}h** across **{sessions}** session(s), **{lines}** lines all told.',
  '🐉 The hoard: **{sessions}** session(s), **{hours}h**, **{lines}** lines.',
  '🎙️ **{lines}** lines on tape across **{sessions}** session(s) (**{hours}h** total).',
];

export const STATS_EMPTY = [
  '📭 No completed sessions yet — nothing to count.',
  "📜 The ledger is blank so far — no finished sessions.",
  '🗝️ Nothing in the vault yet. Finish a session first.',
  "🧾 No totals to report — no completed sessions yet.",
];

export const NPCS_EMPTY = [
  '📭 No NPCs recorded yet.',
  "🧙 Nobody worth writing down has shown up yet.",
  '🗝️ The NPC ledger is empty so far.',
  "🐦 The familiar hasn't met anyone worth noting yet.",
];

// {list}
export const NPCS_HEADER = [
  '🧙 **NPCs met so far:**\n{list}',
  '📜 **The cast so far:**\n{list}',
  '🗝️ **Faces on file:**\n{list}',
  '🧾 **The NPC ledger:**\n{list}',
];

export const LOCATIONS_EMPTY = [
  '📭 No locations recorded yet.',
  "🗺️ Nowhere worth marking on the map yet.",
  '🗝️ The locations ledger is empty so far.',
  "🐦 The familiar hasn't scouted anywhere worth noting yet.",
];

// {list}
export const LOCATIONS_HEADER = [
  '🗺️ **Places visited so far:**\n{list}',
  '📜 **The map so far:**\n{list}',
  '🗝️ **Marked locations:**\n{list}',
  '🧾 **The locations ledger:**\n{list}',
];

export const ARCHIVE_SENT = [
  '🗺️ The full campaign archive — download and open in any browser.',
  '📖 Everything the campaign remembers, in one page.',
  '🧾 The complete archive, ready to open locally.',
  '🔮 A whole campaign, distilled into one file.',
];

export const GENERIC_ERROR = [
  '💥 The spell fizzled: {message}',
  '🧙 Something went wrong in the workshop: {message}',
  '📜 The ink spilled: {message}',
  '🕯️ The candle blew out mid-sentence: {message}',
  "⚗️ That brew didn't go as planned: {message}",
  '🐦 The familiar dropped the message: {message}',
  '🗝️ The lock jammed: {message}',
  '🧾 The scroll tore: {message}',
  '🌙 Something went bump in the dark: {message}',
  '🕰️ Time slipped: {message}',
  '🧠 My memory glitched: {message}',
  '🎙️ Static on the line: {message}',
  '🐉 Even the dragon stumbled: {message}',
  '🗿 The stone cracked: {message}',
  '📯 The herald tripped over their words: {message}',
  '🧝 The chronicler dropped their quill: {message}',
  '⛩️ The ritual faltered: {message}',
  '🪶 The quill snapped: {message}',
  '🔮 The crystal ball cracked: {message}',
  'Something went wrong: {message}',
];
